cmake_minimum_required(VERSION 4.1)

project(core-common-iq-pipeline-stage)

add_subdirectory(agc)
add_subdirectory(base)
add_subdirectory(correction)
add_subdirectory(filter)
add_subdirectory(modulation)
add_subdirectory(monitor)
add_subdirectory(oscillator)
add_subdirectory(resample)
add_subdirectory(s-meter)

