cmake_minimum_required(VERSION 4.1)

set(PROTO_DIR ${CMAKE_SOURCE_DIR}/proto)
set(GEN_DIR ${CMAKE_SOURCE_DIR}/gen)
set(GOOGLE_GEN_DIR ${GEN_DIR}/google)
set(NANOPB_GEN_DIR ${GEN_DIR}/nanopb)

set(INCLUDE_DIR ${CMAKE_SOURCE_DIR}/include)

set(MSG_TYPE_SCALAR 0x1000)
set(MSG_TYPE_VARIANT 0x2000)
set(MSG_BEHAVIOUR_DIRECT 0x0100)
set(MSG_BEHAVIOUR_STEP 0x0200)

math(EXPR MSG_ID_STEP_INT64 "${MSG_TYPE_SCALAR} | ${MSG_BEHAVIOUR_STEP} | 0x0001")
math(EXPR MSG_ID_STEP_FLOAT "${MSG_TYPE_SCALAR} | ${MSG_BEHAVIOUR_STEP} | 0x0002")

add_definitions(
        -DMSG_ID_STEP_INT64=${MSG_ID_STEP_INT64}
        -DMSG_ID_STEP_FLOAT=${MSG_ID_STEP_FLOAT}
)