cmake_minimum_required(VERSION 4.1)

project(core-common)

add_subdirectory(audio)
add_subdirectory(dsp)
add_subdirectory(event)
add_subdirectory(gpio)
add_subdirectory(iq)
add_subdirectory(samples)
add_subdirectory(test-utils)
add_subdirectory(thread)
add_subdirectory(time)
add_subdirectory(usb)
add_subdirectory(transport)
