syntax = "proto3";

//import "nanopb.proto";

package makesdr;


//import "nanopb.proto";

enum MessageTarget {
  MESSAGE_TARGET_NONE = 0;
  MESSAGE_TARGET_RADIO = 2;
  MESSAGE_TARGET_META = 3;

}

enum SplitBandId {
  SPLIT_BAND_NONE = 0;
  SPLIT_BAND_ONE = 1;
  SPLIT_BAND_TWO = 2;
}

enum PipelineId {
  PIPELINE_NONE = 0;
  PIPELINE_A = 1;
  PIPELINE_B = 2;
}

enum ModeType {
  MODE_NONE = 0;
  MODE_AMN = 1;
  MODE_AMW = 2;
  MODE_LSB = 3;
  MODE_USB = 4;
  MODE_FMN = 5;
  MODE_FMW = 6;
  MODE_CWL = 7;
  MODE_CWU = 8;
};

enum AgcSpeed {
  AGC_OFF = 0;
  AGC_SLOW = 1;
  AGC_MEDIUM = 2;
  AGC_FAST = 3;
}

message ModePb {
  ModeType type = 1;
  string name = 2;
  string label = 3;
  int32 lo_cut = 4;
  int32 hi_cut = 5;
  int32 offset = 6;
}

message ModeListPb {
  repeated ModePb modes = 1;
}

message BandPb {
  string name = 1;
  string label = 2;
  int64 lowest_frequency = 3;
  int64 highest_frequency = 4;
  int64 landing_frequency = 5;
  int32 default_fine_step = 6;
  int32 default_coarse_step = 7;
  ModeType default_mode = 8;
}

message BandListPb {
  repeated BandPb bands = 1;
}

message BandCategoryPb {
  string name = 1;
  string label = 2;
  BandListPb bands = 3;
}

message BandCategoryListPb {
  repeated BandCategoryPb categories = 1;
}

message RadioLookupPb {
  BandCategoryListPb bands = 1;
  ModeListPb modes = 2;
}

message SteppableInt64SettingPb {
  int64 value = 1;
  int64 coarse_delta = 2;
  int64 fine_delta = 3;
  bool use_fine = 4;
}

message SteppableFloatSettingPb {
  float value = 1;
  float coarse_delta = 2;
  float fine_delta = 3;
  bool use_fine = 4;
}

//Steppable fields are given a tag over 1000 so that they can be identified when iterating messages

message IqCorrectionSettingsPb {
  SteppableFloatSettingPb amplitude = 1001;
  SteppableFloatSettingPb phase = 1002;
}

message BandRfSettingsPb {
  SteppableInt64SettingPb frequency = 1001;
  SteppableFloatSettingPb gain = 1002;

}

message PipelineRfSettingsPb {
  SteppableInt64SettingPb frequency = 1001;
  optional int32 max_negative_offset = 4;
  optional int32 max_positive_offset = 5;
}

message IfSettingsPb {
  SteppableFloatSettingPb gain = 1001;
  optional uint32 bandwidth = 2;
}

message AfSettingsPb {
  SteppableFloatSettingPb gain = 1001;
}

message ReceiverSettingsPb {
  AfSettingsPb volume = 2;
}

  message TransmitterSettingsPb {
  AfSettingsPb mic = 2;
}

message PipelineSettingsPb {
  oneof mode_or_request {
    ModeType mode_request = 1;
    ModePb mode = 2;
  }
  PipelineRfSettingsPb rf = 3;
  IqCorrectionSettingsPb iq_corrections = 4;
}

message RxPipelineSettingsPb {
  PipelineSettingsPb base = 1;
  optional bool mute = 2;
  optional AgcSpeed agc_speed = 3;
}

message TxPipelineSettingsPb {
  PipelineSettingsPb base = 1;
}

message BasicBandSettingsPb {
  oneof band_or_request {
    string band_request = 1;
    BandPb band = 2;
  }
  oneof mode_or_request {
    ModeType mode_request = 3;
    ModePb mode = 4;
  }
  BandRfSettingsPb rf = 5;
  IfSettingsPb if = 6;
  optional AgcSpeed agc_speed = 7;
}

message BasicIqBandSettingsPb {
  oneof band_or_request {
    string band_request = 1;
    BandPb band = 2;
  }
  BandRfSettingsPb rf = 5;
  IfSettingsPb if = 6;
  RxPipelineSettingsPb focus_pipeline = 10;
}

message DualIqBandSettingsPb {
  oneof band_or_request {
    string band_request = 1;
    BandPb band = 2;
  }
  BandRfSettingsPb rf = 5;
  IfSettingsPb if = 6;
  // This is a dummy pipeline that is used to set either pipeline_a or pipeline_b depending on focus_pipeline_id.
  // It exists for the purpose of path lookups, and is detected as such in code for the above purpose.
  PipelineId focus_pipeline = 10;
  RxPipelineSettingsPb pipeline_a = 11;
  RxPipelineSettingsPb pipeline_b = 12;
  optional bool is_multi_pipeline = 13;
  optional PipelineId focus_pipeline_id = 14;

}

message RxTxDualIqBandSettingsPb {
  oneof band_or_request {
    string band_request = 1;
    BandPb band = 2;
  }
  BandRfSettingsPb rf = 5;
  IfSettingsPb if = 6;
  // This is a dummy pipeline that is used to set either pipeline_a or pipeline_b depending on focus_pipeline_id.
  // It exists for the purpose of path lookups, and is detected as such in code for the above purpose.
  PipelineId focus_pipeline = 10;
  RxPipelineSettingsPb pipeline_a = 11;
  RxPipelineSettingsPb pipeline_b = 12;
  optional bool is_multi_pipeline = 13;
  optional PipelineId focus_pipeline_id = 14;
  TxPipelineSettingsPb tx_pipeline = 15;
  optional PipelineId tx_pipeline_id = 16;

}

message BasicActiveBandSettingsPb {
  BasicBandSettingsPb focus_band = 1;

}

message BasicIqActiveBandSettingsPb {
  BasicIqBandSettingsPb focus_band = 1;

}

message DualIqActiveBandSettingsPb {
  DualIqBandSettingsPb focus_band = 1;
}

message RxTxDualIqActiveBandSettingsPb {
  RxTxDualIqBandSettingsPb focus_band = 1;
}

message SplitBandDualIqActiveBandSettingsPb {
  // This is a pseudo band that is used to set either band_1 or Band_2 depending on focus_band_id.
  // It exists for the purpose of path lookups, and is detected as such in code for the above purpose.
  SplitBandId focus_band = 1;
  RxTxDualIqBandSettingsPb band_1 = 2;
  RxTxDualIqBandSettingsPb band_2 = 3;
  optional SplitBandId focus_band_id = 4;
  optional SplitBandId tx_band_id = 5;
  optional SplitBandId rx_band_id = 6;
  optional bool is_split = 7;


}

message BasicBandSettingsCachePb {
  map<string, BasicBandSettingsPb> band_settings = 1;
}

message BasicIqBandSettingsCachePb {
  map<string, BasicIqBandSettingsPb> band_settings = 1;
}

message DualIqBandSettingsCachePb {
  map<string, DualIqBandSettingsPb> band_settings = 1;
}

message RxTxDualIqBandSettingsCachePb {
  map<string, RxTxDualIqBandSettingsPb> band_settings = 1;
}

// No IQ, just control of a conventional receiver
message BasicRxSettingsPb {
  BasicActiveBandSettingsPb active_bands = 1;
  optional ReceiverSettingsPb receiver = 2;
  optional bool ptt = 4; // Receivers have ptt so that they can respond by muting.
}

// No-frills IQ receiver
message BasicIqRxSettingsPb {
  BasicIqActiveBandSettingsPb active_bands = 1;
  optional ReceiverSettingsPb receiver = 2;
  optional bool ptt = 4;
}

message DualIqRxSettingsPb {
  DualIqActiveBandSettingsPb active_bands = 1;
  optional ReceiverSettingsPb receiver = 2;
  optional bool ptt = 4;
}


// No IQ, just control of a conventional transceiver
message BasicRxTxSettingsPb {
  BasicActiveBandSettingsPb active_bands = 1;
  optional ReceiverSettingsPb receiver = 2;
  optional TransmitterSettingsPb transmitter = 3;
  optional bool ptt = 4;
}

// No-frills IQ transceiver
message BasicIqRxTxSettingsPb {
  BasicIqActiveBandSettingsPb active_bands = 1;
  optional ReceiverSettingsPb receiver = 2;
  optional TransmitterSettingsPb transmitter = 3;
  optional bool ptt = 4;
}

message DualIqRxTxSettingsPb {
  RxTxDualIqActiveBandSettingsPb active_bands = 1;
  optional ReceiverSettingsPb receiver = 2;
  optional TransmitterSettingsPb transmitter = 3;
  optional bool ptt = 4;
}

// Splittable TX and Rx, dual pipelines
message SplitBandDualIqRxTxSettingsPb {
  SplitBandDualIqActiveBandSettingsPb active_bands = 1;
  optional ReceiverSettingsPb receiver = 2;
  optional TransmitterSettingsPb transmitter = 3;
  optional bool ptt = 4;
}

enum FieldUpdateMeaning {
  MEANING_NONE = 0;
  MEANING_VALUE = 1;
  MEANING_DELTA = 2;
}

message FieldUpdatePb {
  repeated uint32 path = 1;
  oneof value_variant {
    string string_value = 2;
    int32 int32_value = 3;
    uint32 uint32_value = 4;
    int64 int64_value = 5;
    float float_value = 6;
    bool bool_value = 7;
  }
  FieldUpdateMeaning meaning = 10;
  bool is_indirect = 11;
  bool is_auto_complete = 12;
  bool is_final = 13;
}