syntax = "proto3";

package makesdr;

import "RadioSettings.proto";

enum RadioPayloadType {
  PAYLOAD_NONE = 0;
  PAYLOAD_SETTINGS_BASIC_RX = 1;
  PAYLOAD_SETTINGS_BASIC_RXTX = 2;
  PAYLOAD_SETTINGS_BASIC_IQ_RX = 3;
  PAYLOAD_SETTINGS_BASIC_IQ_RXTX = 4;
  PAYLOAD_SETTINGS_DUAL_IQ_RX = 5;
  PAYLOAD_SETTINGS_DUAL_IQ_RXTX = 6;
  PAYLOAD_SETTINGS_SPLIT_BAND_DUAL_IQ_RXTX = 7;
  PAYLOAD_FIELD_UPDATE = 10;
  PAYLOAD_MODES = 20;
  PAYLOAD_BANDS = 21;
  PAYLOAD_LOOKUP = 22;
  PAYLOAD_CACHE_BASIC = 30;
  PAYLOAD_CACHE_BASIC_IQ = 31;
  PAYLOAD_CACHE_DUAL_IQ = 32;
  PAYLOAD_CACHE_DUAL_IQ_RXTX = 33;
}

enum RadioPayloadPurpose {
  PURPOSE_NONE = 0;
  PURPOSE_MERGE = 1;
  PURPOSE_REPLACE = 2;
}

enum RadioPayloadSource {
  SOURCE_UNKNOWN = 0;
  SOURCE_BACK_END = 1;
  SOURCE_FRONT_END = 2;
}

message RadioPayloadHeaderPb {
  RadioPayloadType payloadType = 1;
  RadioPayloadSource source = 2;
  RadioPayloadPurpose purpose = 3;
}

message RadioPayloadBasePb {
    RadioPayloadHeaderPb header = 1;
}


message BasicRxSettingsPayloadPb {
  RadioPayloadHeaderPb header = 1;
  BasicRxSettingsPb body = 2;
}

message BasicIqRxSettingsPayloadPb {
  RadioPayloadHeaderPb header = 1;
  BasicIqRxSettingsPb body = 2;
}

message DualIqRxSettingsPayloadPb {
  RadioPayloadHeaderPb header = 1;
  DualIqRxSettingsPb body = 2;
}

message BasicRxTxSettingsPayloadPb {
  RadioPayloadHeaderPb header = 1;
  BasicRxTxSettingsPb body = 2;
}

message BasicIqRxTxSettingsPayloadPb {
  RadioPayloadHeaderPb header = 1;
  BasicIqRxTxSettingsPb body = 2;
}

message DualIqRxTxSettingsPayloadPb {
  RadioPayloadHeaderPb header = 1;
  DualIqRxTxSettingsPb body = 2;
}

message SplitBandDualIqRxTxSettingsPayloadPb {
  RadioPayloadHeaderPb header = 1;
  SplitBandDualIqRxTxSettingsPb body = 2;
}

message ModesPayloadPb {
  RadioPayloadHeaderPb header = 1;
  ModeListPb body = 2;
}

message BandsPayloadPb {
  RadioPayloadHeaderPb header = 1;
  BandCategoryListPb body = 2;
}

message RadioLookupPayloadPb {
  RadioPayloadHeaderPb header = 1;
  RadioLookupPb body = 2;
}

message RadioCacheBasicPayloadPb {
  RadioPayloadHeaderPb header = 1;
  BasicBandSettingsCachePb body = 2;
}

message RadioCacheBasicIqPayloadPb {
  RadioPayloadHeaderPb header = 1;
  BasicIqBandSettingsCachePb body = 2;
}

message RadioCacheDualIqPayloadPb {
  RadioPayloadHeaderPb header = 1;
  DualIqBandSettingsCachePb body = 2;
}

message RadioCacheRxTxDualIqPayloadPb {
  RadioPayloadHeaderPb header = 1;
  RxTxDualIqBandSettingsCachePb body = 2;
}

message FieldUpdatePayloadPb {
  RadioPayloadHeaderPb header = 1;
  FieldUpdatePb body = 2;
}

