#pragma once

enum EventId
{
  EVENT_SETTINGS_UPDATE = 1100,
  EVENT_SETTINGS_BASIC_RX,
  EVENT_SETTINGS_BASIC_RXTX,
  EVENT_SETTINGS_BASIC_IQ_RX,
  EVENT_SETTINGS_BASIC_IQ_RXTX,
  EVENT_SETTINGS_DUAL_IQ_RX,
  EVENT_SETTINGS_DUAL_IQ_RXTX,
  EVENT_SETTINGS_DUAL_IQ_SPLIT,
  EVENT_SETTINGS_RADIO_FIRST = EVENT_SETTINGS_BASIC_RX,
  EVENT_SETTINGS_RADIO_LAST = EVENT_SETTINGS_DUAL_IQ_SPLIT,
  EVENT_IQ_RX,
  EVENT_IQ_TX,
  EVENT_AUDIO_RX,
  EVENT_AUDIO_TX,
  EVENT_METER_RX,
  EVENT_METER_RX_IQ,
  EVENT_METER_TX,
  EVENT_METER_TX_IQ
};