#pragma once

enum class ResultCode
{
  OK,
  ERR_SETTING_PATH_NOT_FOUND,
  ERR_SETTING_DOTTED_STRING_NOT_VALID,
  ERR_SETTING_EMPTY_MESSAGE,
  ERR_SETTING_FIELD_NOT_FOUND,
  ERR_SETTING_PATH_TOO_LONG,
  ERR_SETTING_POINTER_FIELD_NULL,
  ERR_SETTING_UNKNOWN_TAG,
  ERR_SETTING_EXPECT_BOOL,
  ERR_SETTING_EXPECT_INT32,
  ERR_SETTING_EXPECT_UINT32,
  ERR_SETTING_EXPECT_INT64,
  ERR_SETTING_EXPECT_UINT64,
  ERR_SETTING_EXPECT_FLOAT,
  ERR_SETTING_EXPECT_DOUBLE,
  ERR_SETTING_EXPECT_STRING,
  ERR_SETTING_STRING_TOO_LONG,
  ERR_SETTING_UNSUPPORTED_TYPE
};