cmake_minimum_required(VERSION 4.1)

project(ui-qt-widgets)

add_subdirectory(BandDialog)
add_subdirectory(Charts)
add_subdirectory(FrequencyPanel)
add_subdirectory(MiniVfoToolbar)
add_subdirectory(NumberReadout)
add_subdirectory(PropertySetter)
add_subdirectory(ScaleRenderer)
add_subdirectory(Stepper)
add_subdirectory(SMeter)
add_subdirectory(VfoReadout)
