/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_RADIOSETTINGS_RADIOPAYLOADS_PB_H_INCLUDED
#define PB_RADIOSETTINGS_RADIOPAYLOADS_PB_H_INCLUDED
#include <pb.h>
#include "RadioSettings.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _RadioSettings_RadioPayloadType {
    RadioSettings_RadioPayloadType_PAYLOAD_NONE = 0,
    RadioSettings_RadioPayloadType_PAYLOAD_SETTINGS = 1,
    RadioSettings_RadioPayloadType_PAYLOAD_META = 3,
    RadioSettings_RadioPayloadType_PAYLOAD_CACHE = 4
} RadioSettings_RadioPayloadType;

typedef enum _RadioSettings_RadioPayloadPurpose {
    RadioSettings_RadioPayloadPurpose_PURPOSE_NONE = 0,
    RadioSettings_RadioPayloadPurpose_PURPOSE_MERGE = 1,
    RadioSettings_RadioPayloadPurpose_PURPOSE_REPLACE = 2
} RadioSettings_RadioPayloadPurpose;

/* Struct definitions */
typedef struct _RadioSettings_RadioSettingsPayloadPb {
    RadioSettings_RadioPayloadType payloadType;
    RadioSettings_RadioPayloadPurpose purpose;
    bool has_settings;
    RadioSettings_RadioSettingsPb settings; /* oneof payload {
    RadioSettingsPb settings = 2;
    RadioMetaPb meta = 3;
    BandSettingsCachePb cache = 4;
  } */
} RadioSettings_RadioSettingsPayloadPb;

typedef struct _RadioSettings_RadioMetaPayloadPb {
    RadioSettings_RadioPayloadType payloadType;
    bool has_meta;
    RadioSettings_RadioMetaPb meta;
} RadioSettings_RadioMetaPayloadPb;

typedef struct _RadioSettings_RadioCachePayloadPb {
    RadioSettings_RadioPayloadType payloadType;
    bool has_cache;
    RadioSettings_RadioMetaPb cache;
} RadioSettings_RadioCachePayloadPb;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _RadioSettings_RadioPayloadType_MIN RadioSettings_RadioPayloadType_PAYLOAD_NONE
#define _RadioSettings_RadioPayloadType_MAX RadioSettings_RadioPayloadType_PAYLOAD_CACHE
#define _RadioSettings_RadioPayloadType_ARRAYSIZE ((RadioSettings_RadioPayloadType)(RadioSettings_RadioPayloadType_PAYLOAD_CACHE+1))

#define _RadioSettings_RadioPayloadPurpose_MIN RadioSettings_RadioPayloadPurpose_PURPOSE_NONE
#define _RadioSettings_RadioPayloadPurpose_MAX RadioSettings_RadioPayloadPurpose_PURPOSE_REPLACE
#define _RadioSettings_RadioPayloadPurpose_ARRAYSIZE ((RadioSettings_RadioPayloadPurpose)(RadioSettings_RadioPayloadPurpose_PURPOSE_REPLACE+1))

#define RadioSettings_RadioSettingsPayloadPb_payloadType_ENUMTYPE RadioSettings_RadioPayloadType
#define RadioSettings_RadioSettingsPayloadPb_purpose_ENUMTYPE RadioSettings_RadioPayloadPurpose

#define RadioSettings_RadioMetaPayloadPb_payloadType_ENUMTYPE RadioSettings_RadioPayloadType

#define RadioSettings_RadioCachePayloadPb_payloadType_ENUMTYPE RadioSettings_RadioPayloadType


/* Initializer values for message structs */
#define RadioSettings_RadioSettingsPayloadPb_init_default {_RadioSettings_RadioPayloadType_MIN, _RadioSettings_RadioPayloadPurpose_MIN, false, RadioSettings_RadioSettingsPb_init_default}
#define RadioSettings_RadioMetaPayloadPb_init_default {_RadioSettings_RadioPayloadType_MIN, false, RadioSettings_RadioMetaPb_init_default}
#define RadioSettings_RadioCachePayloadPb_init_default {_RadioSettings_RadioPayloadType_MIN, false, RadioSettings_RadioMetaPb_init_default}
#define RadioSettings_RadioSettingsPayloadPb_init_zero {_RadioSettings_RadioPayloadType_MIN, _RadioSettings_RadioPayloadPurpose_MIN, false, RadioSettings_RadioSettingsPb_init_zero}
#define RadioSettings_RadioMetaPayloadPb_init_zero {_RadioSettings_RadioPayloadType_MIN, false, RadioSettings_RadioMetaPb_init_zero}
#define RadioSettings_RadioCachePayloadPb_init_zero {_RadioSettings_RadioPayloadType_MIN, false, RadioSettings_RadioMetaPb_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define RadioSettings_RadioSettingsPayloadPb_payloadType_tag 1
#define RadioSettings_RadioSettingsPayloadPb_purpose_tag 2
#define RadioSettings_RadioSettingsPayloadPb_settings_tag 3
#define RadioSettings_RadioMetaPayloadPb_payloadType_tag 1
#define RadioSettings_RadioMetaPayloadPb_meta_tag 2
#define RadioSettings_RadioCachePayloadPb_payloadType_tag 1
#define RadioSettings_RadioCachePayloadPb_cache_tag 2

/* Struct field encoding specification for nanopb */
#define RadioSettings_RadioSettingsPayloadPb_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    payloadType,       1) \
X(a, STATIC,   SINGULAR, UENUM,    purpose,           2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  settings,          3)
#define RadioSettings_RadioSettingsPayloadPb_CALLBACK NULL
#define RadioSettings_RadioSettingsPayloadPb_DEFAULT NULL
#define RadioSettings_RadioSettingsPayloadPb_settings_MSGTYPE RadioSettings_RadioSettingsPb

#define RadioSettings_RadioMetaPayloadPb_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    payloadType,       1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  meta,              2)
#define RadioSettings_RadioMetaPayloadPb_CALLBACK NULL
#define RadioSettings_RadioMetaPayloadPb_DEFAULT NULL
#define RadioSettings_RadioMetaPayloadPb_meta_MSGTYPE RadioSettings_RadioMetaPb

#define RadioSettings_RadioCachePayloadPb_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    payloadType,       1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  cache,             2)
#define RadioSettings_RadioCachePayloadPb_CALLBACK NULL
#define RadioSettings_RadioCachePayloadPb_DEFAULT NULL
#define RadioSettings_RadioCachePayloadPb_cache_MSGTYPE RadioSettings_RadioMetaPb

extern const pb_msgdesc_t RadioSettings_RadioSettingsPayloadPb_msg;
extern const pb_msgdesc_t RadioSettings_RadioMetaPayloadPb_msg;
extern const pb_msgdesc_t RadioSettings_RadioCachePayloadPb_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define RadioSettings_RadioSettingsPayloadPb_fields &RadioSettings_RadioSettingsPayloadPb_msg
#define RadioSettings_RadioMetaPayloadPb_fields &RadioSettings_RadioMetaPayloadPb_msg
#define RadioSettings_RadioCachePayloadPb_fields &RadioSettings_RadioCachePayloadPb_msg

/* Maximum encoded size of messages (where known) */
#define RADIOSETTINGS_RADIOPAYLOADS_PB_H_MAX_SIZE RadioSettings_RadioMetaPayloadPb_size
#define RadioSettings_RadioCachePayloadPb_size   9055
#define RadioSettings_RadioMetaPayloadPb_size    9055
#define RadioSettings_RadioSettingsPayloadPb_size 1568

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
