/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_MAKESDR_RADIOSETTINGS_PB_H_INCLUDED
#define PB_MAKESDR_RADIOSETTINGS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _makesdr_MessageTarget {
    makesdr_MessageTarget_MESSAGE_TARGET_NONE = 0,
    makesdr_MessageTarget_MESSAGE_TARGET_RADIO = 2,
    makesdr_MessageTarget_MESSAGE_TARGET_META = 3
} makesdr_MessageTarget;

typedef enum _makesdr_SplitBandId {
    makesdr_SplitBandId_SPLIT_BAND_NONE = 0,
    makesdr_SplitBandId_SPLIT_BAND_ONE = 1,
    makesdr_SplitBandId_SPLIT_BAND_TWO = 2
} makesdr_SplitBandId;

typedef enum _makesdr_PipelineId {
    makesdr_PipelineId_PIPELINE_NONE = 0,
    makesdr_PipelineId_PIPELINE_A = 1,
    makesdr_PipelineId_PIPELINE_B = 2
} makesdr_PipelineId;

typedef enum _makesdr_ModeType {
    makesdr_ModeType_MODE_NONE = 0,
    makesdr_ModeType_MODE_AMN = 1,
    makesdr_ModeType_MODE_AMW = 2,
    makesdr_ModeType_MODE_LSB = 3,
    makesdr_ModeType_MODE_USB = 4,
    makesdr_ModeType_MODE_FMN = 5,
    makesdr_ModeType_MODE_FMW = 6,
    makesdr_ModeType_MODE_CWL = 7,
    makesdr_ModeType_MODE_CWU = 8
} makesdr_ModeType;

typedef enum _makesdr_AgcSpeed {
    makesdr_AgcSpeed_AGC_OFF = 0,
    makesdr_AgcSpeed_AGC_SLOW = 1,
    makesdr_AgcSpeed_AGC_MEDIUM = 2,
    makesdr_AgcSpeed_AGC_FAST = 3
} makesdr_AgcSpeed;

typedef enum _makesdr_FieldUpdateMeaning {
    makesdr_FieldUpdateMeaning_MEANING_NONE = 0,
    makesdr_FieldUpdateMeaning_MEANING_VALUE = 1,
    makesdr_FieldUpdateMeaning_MEANING_DELTA = 2
} makesdr_FieldUpdateMeaning;

/* Struct definitions */
typedef struct _makesdr_ModePb {
    makesdr_ModeType type;
    char name[8];
    char label[15];
    int32_t lo_cut;
    int32_t hi_cut;
    int32_t offset;
} makesdr_ModePb;

typedef struct _makesdr_ModeListPb {
    pb_size_t modes_count;
    makesdr_ModePb modes[10];
} makesdr_ModeListPb;

typedef struct _makesdr_BandPb {
    char name[8];
    char label[10];
    int64_t lowest_frequency;
    int64_t highest_frequency;
    int64_t landing_frequency;
    int32_t default_fine_step;
    int32_t default_coarse_step;
    makesdr_ModeType default_mode;
} makesdr_BandPb;

typedef struct _makesdr_BandListPb {
    pb_size_t bands_count;
    makesdr_BandPb bands[13];
} makesdr_BandListPb;

typedef struct _makesdr_BandCategoryPb {
    char name[8];
    char label[10];
    bool has_bands;
    makesdr_BandListPb bands;
} makesdr_BandCategoryPb;

typedef struct _makesdr_BandCategoryListPb {
    pb_size_t categories_count;
    makesdr_BandCategoryPb categories[8];
} makesdr_BandCategoryListPb;

typedef struct _makesdr_RadioLookupPb {
    bool has_bands;
    makesdr_BandCategoryListPb bands;
    bool has_modes;
    makesdr_ModeListPb modes;
} makesdr_RadioLookupPb;

typedef struct _makesdr_SteppableInt64SettingPb {
    int64_t value;
    int64_t coarse_delta;
    int64_t fine_delta;
    bool use_fine;
} makesdr_SteppableInt64SettingPb;

typedef struct _makesdr_SteppableFloatSettingPb {
    float value;
    float coarse_delta;
    float fine_delta;
    bool use_fine;
} makesdr_SteppableFloatSettingPb;

typedef struct _makesdr_IqCorrectionSettingsPb {
    bool has_amplitude;
    makesdr_SteppableFloatSettingPb amplitude;
    bool has_phase;
    makesdr_SteppableFloatSettingPb phase;
} makesdr_IqCorrectionSettingsPb;

typedef struct _makesdr_BandRfSettingsPb {
    bool has_frequency;
    makesdr_SteppableInt64SettingPb frequency;
    bool has_gain;
    makesdr_SteppableFloatSettingPb gain;
} makesdr_BandRfSettingsPb;

typedef struct _makesdr_PipelineRfSettingsPb {
    bool has_max_negative_offset;
    int32_t max_negative_offset;
    bool has_max_positive_offset;
    int32_t max_positive_offset;
    bool has_frequency;
    makesdr_SteppableInt64SettingPb frequency;
} makesdr_PipelineRfSettingsPb;

typedef struct _makesdr_IfSettingsPb {
    bool has_bandwidth;
    uint32_t bandwidth;
    bool has_gain;
    makesdr_SteppableFloatSettingPb gain;
} makesdr_IfSettingsPb;

typedef struct _makesdr_AfSettingsPb {
    bool has_gain;
    makesdr_SteppableFloatSettingPb gain;
} makesdr_AfSettingsPb;

typedef struct _makesdr_ReceiverSettingsPb {
    bool has_volume;
    makesdr_AfSettingsPb volume;
} makesdr_ReceiverSettingsPb;

typedef struct _makesdr_TransmitterSettingsPb {
    bool has_mic;
    makesdr_AfSettingsPb mic;
} makesdr_TransmitterSettingsPb;

typedef struct _makesdr_PipelineSettingsPb {
    pb_size_t which_mode_or_request;
    union _makesdr_PipelineSettingsPb_mode_or_request {
        makesdr_ModeType mode_request;
        makesdr_ModePb mode;
    } mode_or_request;
    bool has_rf;
    makesdr_PipelineRfSettingsPb rf;
    bool has_iq_corrections;
    makesdr_IqCorrectionSettingsPb iq_corrections;
} makesdr_PipelineSettingsPb;

typedef struct _makesdr_RxPipelineSettingsPb {
    bool has_base;
    makesdr_PipelineSettingsPb base;
    bool has_mute;
    bool mute;
    bool has_agc_speed;
    makesdr_AgcSpeed agc_speed;
} makesdr_RxPipelineSettingsPb;

typedef struct _makesdr_TxPipelineSettingsPb {
    bool has_base;
    makesdr_PipelineSettingsPb base;
} makesdr_TxPipelineSettingsPb;

typedef struct _makesdr_BasicBandSettingsPb {
    pb_size_t which_band_or_request;
    union _makesdr_BasicBandSettingsPb_band_or_request {
        char band_request[8];
        makesdr_BandPb band;
    } band_or_request;
    pb_size_t which_mode_or_request;
    union _makesdr_BasicBandSettingsPb_mode_or_request {
        makesdr_ModeType mode_request;
        makesdr_ModePb mode;
    } mode_or_request;
    bool has_rf;
    makesdr_BandRfSettingsPb rf;
    bool has_if_;
    makesdr_IfSettingsPb if_;
    bool has_agc_speed;
    makesdr_AgcSpeed agc_speed;
} makesdr_BasicBandSettingsPb;

typedef struct _makesdr_BasicIqBandSettingsPb {
    pb_size_t which_band_or_request;
    union _makesdr_BasicIqBandSettingsPb_band_or_request {
        char band_request[8];
        makesdr_BandPb band;
    } band_or_request;
    bool has_rf;
    makesdr_BandRfSettingsPb rf;
    bool has_if_;
    makesdr_IfSettingsPb if_;
    bool has_focus_pipeline;
    makesdr_RxPipelineSettingsPb focus_pipeline;
} makesdr_BasicIqBandSettingsPb;

typedef struct _makesdr_DualIqBandSettingsPb {
    pb_size_t which_band_or_request;
    union _makesdr_DualIqBandSettingsPb_band_or_request {
        char band_request[8];
        makesdr_BandPb band;
    } band_or_request;
    bool has_rf;
    makesdr_BandRfSettingsPb rf;
    bool has_if_;
    makesdr_IfSettingsPb if_;
    /* This is a dummy pipeline that is used to set either pipeline_a or pipeline_b depending on focus_pipeline_id.
 It exists for the purpose of path lookups, and is detected as such in code for the above purpose. */
    makesdr_PipelineId focus_pipeline;
    bool has_pipeline_a;
    makesdr_RxPipelineSettingsPb pipeline_a;
    bool has_pipeline_b;
    makesdr_RxPipelineSettingsPb pipeline_b;
    bool has_is_multi_pipeline;
    bool is_multi_pipeline;
    bool has_focus_pipeline_id;
    makesdr_PipelineId focus_pipeline_id;
} makesdr_DualIqBandSettingsPb;

typedef struct _makesdr_RxTxDualIqBandSettingsPb {
    pb_size_t which_band_or_request;
    union _makesdr_RxTxDualIqBandSettingsPb_band_or_request {
        char band_request[8];
        makesdr_BandPb band;
    } band_or_request;
    bool has_rf;
    makesdr_BandRfSettingsPb rf;
    bool has_if_;
    makesdr_IfSettingsPb if_;
    /* This is a dummy pipeline that is used to set either pipeline_a or pipeline_b depending on focus_pipeline_id.
 It exists for the purpose of path lookups, and is detected as such in code for the above purpose. */
    makesdr_PipelineId focus_pipeline;
    bool has_pipeline_a;
    makesdr_RxPipelineSettingsPb pipeline_a;
    bool has_pipeline_b;
    makesdr_RxPipelineSettingsPb pipeline_b;
    bool has_is_multi_pipeline;
    bool is_multi_pipeline;
    bool has_focus_pipeline_id;
    makesdr_PipelineId focus_pipeline_id;
    bool has_tx_pipeline;
    makesdr_TxPipelineSettingsPb tx_pipeline;
    bool has_tx_pipeline_id;
    makesdr_PipelineId tx_pipeline_id;
} makesdr_RxTxDualIqBandSettingsPb;

typedef struct _makesdr_BasicActiveBandSettingsPb {
    bool has_focus_band;
    makesdr_BasicBandSettingsPb focus_band;
} makesdr_BasicActiveBandSettingsPb;

typedef struct _makesdr_BasicIqActiveBandSettingsPb {
    bool has_focus_band;
    makesdr_BasicIqBandSettingsPb focus_band;
} makesdr_BasicIqActiveBandSettingsPb;

typedef struct _makesdr_DualIqActiveBandSettingsPb {
    bool has_focus_band;
    makesdr_DualIqBandSettingsPb focus_band;
} makesdr_DualIqActiveBandSettingsPb;

typedef struct _makesdr_RxTxDualIqActiveBandSettingsPb {
    bool has_focus_band;
    makesdr_RxTxDualIqBandSettingsPb focus_band;
} makesdr_RxTxDualIqActiveBandSettingsPb;

typedef struct _makesdr_SplitBandDualIqActiveBandSettingsPb {
    /* This is a pseudo band that is used to set either band_1 or Band_2 depending on focus_band_id.
 It exists for the purpose of path lookups, and is detected as such in code for the above purpose. */
    makesdr_SplitBandId focus_band;
    bool has_band_1;
    makesdr_RxTxDualIqBandSettingsPb band_1;
    bool has_band_2;
    makesdr_RxTxDualIqBandSettingsPb band_2;
    bool has_focus_band_id;
    makesdr_SplitBandId focus_band_id;
    bool has_tx_band_id;
    makesdr_SplitBandId tx_band_id;
    bool has_rx_band_id;
    makesdr_SplitBandId rx_band_id;
    bool has_is_split;
    bool is_split;
} makesdr_SplitBandDualIqActiveBandSettingsPb;

typedef struct _makesdr_BasicBandSettingsCachePb_BandSettingsEntry {
    char key[8];
    bool has_value;
    makesdr_BasicBandSettingsPb value;
} makesdr_BasicBandSettingsCachePb_BandSettingsEntry;

typedef struct _makesdr_BasicBandSettingsCachePb {
    pb_size_t band_settings_count;
    makesdr_BasicBandSettingsCachePb_BandSettingsEntry band_settings[10];
} makesdr_BasicBandSettingsCachePb;

typedef struct _makesdr_BasicIqBandSettingsCachePb_BandSettingsEntry {
    char key[8];
    bool has_value;
    makesdr_BasicIqBandSettingsPb value;
} makesdr_BasicIqBandSettingsCachePb_BandSettingsEntry;

typedef struct _makesdr_BasicIqBandSettingsCachePb {
    pb_size_t band_settings_count;
    makesdr_BasicIqBandSettingsCachePb_BandSettingsEntry band_settings[10];
} makesdr_BasicIqBandSettingsCachePb;

typedef struct _makesdr_DualIqBandSettingsCachePb_BandSettingsEntry {
    char key[8];
    bool has_value;
    makesdr_DualIqBandSettingsPb value;
} makesdr_DualIqBandSettingsCachePb_BandSettingsEntry;

typedef struct _makesdr_DualIqBandSettingsCachePb {
    pb_size_t band_settings_count;
    makesdr_DualIqBandSettingsCachePb_BandSettingsEntry band_settings[10];
} makesdr_DualIqBandSettingsCachePb;

typedef struct _makesdr_RxTxDualIqBandSettingsCachePb_BandSettingsEntry {
    char key[8];
    bool has_value;
    makesdr_RxTxDualIqBandSettingsPb value;
} makesdr_RxTxDualIqBandSettingsCachePb_BandSettingsEntry;

typedef struct _makesdr_RxTxDualIqBandSettingsCachePb {
    pb_size_t band_settings_count;
    makesdr_RxTxDualIqBandSettingsCachePb_BandSettingsEntry band_settings[10];
} makesdr_RxTxDualIqBandSettingsCachePb;

/* No IQ, just control of a conventional receiver */
typedef struct _makesdr_BasicRxSettingsPb {
    bool has_active_bands;
    makesdr_BasicActiveBandSettingsPb active_bands;
    bool has_receiver;
    makesdr_ReceiverSettingsPb receiver;
    bool has_ptt;
    bool ptt; /* Receivers have ptt so that they can respond by muting. */
} makesdr_BasicRxSettingsPb;

/* No-frills IQ receiver */
typedef struct _makesdr_BasicIqRxSettingsPb {
    bool has_active_bands;
    makesdr_BasicIqActiveBandSettingsPb active_bands;
    bool has_receiver;
    makesdr_ReceiverSettingsPb receiver;
    bool has_ptt;
    bool ptt;
} makesdr_BasicIqRxSettingsPb;

typedef struct _makesdr_DualIqRxSettingsPb {
    bool has_active_bands;
    makesdr_DualIqActiveBandSettingsPb active_bands;
    bool has_receiver;
    makesdr_ReceiverSettingsPb receiver;
    bool has_ptt;
    bool ptt;
} makesdr_DualIqRxSettingsPb;

/* No IQ, just control of a conventional transceiver */
typedef struct _makesdr_BasicRxTxSettingsPb {
    bool has_active_bands;
    makesdr_BasicActiveBandSettingsPb active_bands;
    bool has_receiver;
    makesdr_ReceiverSettingsPb receiver;
    bool has_transmitter;
    makesdr_TransmitterSettingsPb transmitter;
    bool has_ptt;
    bool ptt;
} makesdr_BasicRxTxSettingsPb;

/* No-frills IQ transceiver */
typedef struct _makesdr_BasicIqRxTxSettingsPb {
    bool has_active_bands;
    makesdr_BasicIqActiveBandSettingsPb active_bands;
    bool has_receiver;
    makesdr_ReceiverSettingsPb receiver;
    bool has_transmitter;
    makesdr_TransmitterSettingsPb transmitter;
    bool has_ptt;
    bool ptt;
} makesdr_BasicIqRxTxSettingsPb;

typedef struct _makesdr_DualIqRxTxSettingsPb {
    bool has_active_bands;
    makesdr_RxTxDualIqActiveBandSettingsPb active_bands;
    bool has_receiver;
    makesdr_ReceiverSettingsPb receiver;
    bool has_transmitter;
    makesdr_TransmitterSettingsPb transmitter;
    bool has_ptt;
    bool ptt;
} makesdr_DualIqRxTxSettingsPb;

/* Splittable TX and Rx, dual pipelines */
typedef struct _makesdr_SplitBandDualIqRxTxSettingsPb {
    bool has_active_bands;
    makesdr_SplitBandDualIqActiveBandSettingsPb active_bands;
    bool has_receiver;
    makesdr_ReceiverSettingsPb receiver;
    bool has_transmitter;
    makesdr_TransmitterSettingsPb transmitter;
    bool has_ptt;
    bool ptt;
} makesdr_SplitBandDualIqRxTxSettingsPb;

typedef struct _makesdr_FieldUpdatePb {
    pb_size_t path_count;
    uint32_t path[8];
    pb_size_t which_value_variant;
    union _makesdr_FieldUpdatePb_value_variant {
        char string_value[8];
        int32_t int32_value;
        uint32_t uint32_value;
        int64_t int64_value;
        float float_value;
        bool bool_value;
    } value_variant;
    makesdr_FieldUpdateMeaning meaning;
    bool is_indirect;
    bool is_auto_complete;
    bool is_final;
} makesdr_FieldUpdatePb;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _makesdr_MessageTarget_MIN makesdr_MessageTarget_MESSAGE_TARGET_NONE
#define _makesdr_MessageTarget_MAX makesdr_MessageTarget_MESSAGE_TARGET_META
#define _makesdr_MessageTarget_ARRAYSIZE ((makesdr_MessageTarget)(makesdr_MessageTarget_MESSAGE_TARGET_META+1))

#define _makesdr_SplitBandId_MIN makesdr_SplitBandId_SPLIT_BAND_NONE
#define _makesdr_SplitBandId_MAX makesdr_SplitBandId_SPLIT_BAND_TWO
#define _makesdr_SplitBandId_ARRAYSIZE ((makesdr_SplitBandId)(makesdr_SplitBandId_SPLIT_BAND_TWO+1))

#define _makesdr_PipelineId_MIN makesdr_PipelineId_PIPELINE_NONE
#define _makesdr_PipelineId_MAX makesdr_PipelineId_PIPELINE_B
#define _makesdr_PipelineId_ARRAYSIZE ((makesdr_PipelineId)(makesdr_PipelineId_PIPELINE_B+1))

#define _makesdr_ModeType_MIN makesdr_ModeType_MODE_NONE
#define _makesdr_ModeType_MAX makesdr_ModeType_MODE_CWU
#define _makesdr_ModeType_ARRAYSIZE ((makesdr_ModeType)(makesdr_ModeType_MODE_CWU+1))

#define _makesdr_AgcSpeed_MIN makesdr_AgcSpeed_AGC_OFF
#define _makesdr_AgcSpeed_MAX makesdr_AgcSpeed_AGC_FAST
#define _makesdr_AgcSpeed_ARRAYSIZE ((makesdr_AgcSpeed)(makesdr_AgcSpeed_AGC_FAST+1))

#define _makesdr_FieldUpdateMeaning_MIN makesdr_FieldUpdateMeaning_MEANING_NONE
#define _makesdr_FieldUpdateMeaning_MAX makesdr_FieldUpdateMeaning_MEANING_DELTA
#define _makesdr_FieldUpdateMeaning_ARRAYSIZE ((makesdr_FieldUpdateMeaning)(makesdr_FieldUpdateMeaning_MEANING_DELTA+1))

#define makesdr_ModePb_type_ENUMTYPE makesdr_ModeType


#define makesdr_BandPb_default_mode_ENUMTYPE makesdr_ModeType














#define makesdr_PipelineSettingsPb_mode_or_request_mode_request_ENUMTYPE makesdr_ModeType

#define makesdr_RxPipelineSettingsPb_agc_speed_ENUMTYPE makesdr_AgcSpeed


#define makesdr_BasicBandSettingsPb_mode_or_request_mode_request_ENUMTYPE makesdr_ModeType
#define makesdr_BasicBandSettingsPb_agc_speed_ENUMTYPE makesdr_AgcSpeed


#define makesdr_DualIqBandSettingsPb_focus_pipeline_ENUMTYPE makesdr_PipelineId
#define makesdr_DualIqBandSettingsPb_focus_pipeline_id_ENUMTYPE makesdr_PipelineId

#define makesdr_RxTxDualIqBandSettingsPb_focus_pipeline_ENUMTYPE makesdr_PipelineId
#define makesdr_RxTxDualIqBandSettingsPb_focus_pipeline_id_ENUMTYPE makesdr_PipelineId
#define makesdr_RxTxDualIqBandSettingsPb_tx_pipeline_id_ENUMTYPE makesdr_PipelineId





#define makesdr_SplitBandDualIqActiveBandSettingsPb_focus_band_ENUMTYPE makesdr_SplitBandId
#define makesdr_SplitBandDualIqActiveBandSettingsPb_focus_band_id_ENUMTYPE makesdr_SplitBandId
#define makesdr_SplitBandDualIqActiveBandSettingsPb_tx_band_id_ENUMTYPE makesdr_SplitBandId
#define makesdr_SplitBandDualIqActiveBandSettingsPb_rx_band_id_ENUMTYPE makesdr_SplitBandId
















#define makesdr_FieldUpdatePb_meaning_ENUMTYPE makesdr_FieldUpdateMeaning


/* Initializer values for message structs */
#define makesdr_ModePb_init_default              {_makesdr_ModeType_MIN, "", "", 0, 0, 0}
#define makesdr_ModeListPb_init_default          {0, {makesdr_ModePb_init_default, makesdr_ModePb_init_default, makesdr_ModePb_init_default, makesdr_ModePb_init_default, makesdr_ModePb_init_default, makesdr_ModePb_init_default, makesdr_ModePb_init_default, makesdr_ModePb_init_default, makesdr_ModePb_init_default, makesdr_ModePb_init_default}}
#define makesdr_BandPb_init_default              {"", "", 0, 0, 0, 0, 0, _makesdr_ModeType_MIN}
#define makesdr_BandListPb_init_default          {0, {makesdr_BandPb_init_default, makesdr_BandPb_init_default, makesdr_BandPb_init_default, makesdr_BandPb_init_default, makesdr_BandPb_init_default, makesdr_BandPb_init_default, makesdr_BandPb_init_default, makesdr_BandPb_init_default, makesdr_BandPb_init_default, makesdr_BandPb_init_default, makesdr_BandPb_init_default, makesdr_BandPb_init_default, makesdr_BandPb_init_default}}
#define makesdr_BandCategoryPb_init_default      {"", "", false, makesdr_BandListPb_init_default}
#define makesdr_BandCategoryListPb_init_default  {0, {makesdr_BandCategoryPb_init_default, makesdr_BandCategoryPb_init_default, makesdr_BandCategoryPb_init_default, makesdr_BandCategoryPb_init_default, makesdr_BandCategoryPb_init_default, makesdr_BandCategoryPb_init_default, makesdr_BandCategoryPb_init_default, makesdr_BandCategoryPb_init_default}}
#define makesdr_RadioLookupPb_init_default       {false, makesdr_BandCategoryListPb_init_default, false, makesdr_ModeListPb_init_default}
#define makesdr_SteppableInt64SettingPb_init_default {0, 0, 0, 0}
#define makesdr_SteppableFloatSettingPb_init_default {0, 0, 0, 0}
#define makesdr_IqCorrectionSettingsPb_init_default {false, makesdr_SteppableFloatSettingPb_init_default, false, makesdr_SteppableFloatSettingPb_init_default}
#define makesdr_BandRfSettingsPb_init_default    {false, makesdr_SteppableInt64SettingPb_init_default, false, makesdr_SteppableFloatSettingPb_init_default}
#define makesdr_PipelineRfSettingsPb_init_default {false, 0, false, 0, false, makesdr_SteppableInt64SettingPb_init_default}
#define makesdr_IfSettingsPb_init_default        {false, 0, false, makesdr_SteppableFloatSettingPb_init_default}
#define makesdr_AfSettingsPb_init_default        {false, makesdr_SteppableFloatSettingPb_init_default}
#define makesdr_ReceiverSettingsPb_init_default  {false, makesdr_AfSettingsPb_init_default}
#define makesdr_TransmitterSettingsPb_init_default {false, makesdr_AfSettingsPb_init_default}
#define makesdr_PipelineSettingsPb_init_default  {0, {_makesdr_ModeType_MIN}, false, makesdr_PipelineRfSettingsPb_init_default, false, makesdr_IqCorrectionSettingsPb_init_default}
#define makesdr_RxPipelineSettingsPb_init_default {false, makesdr_PipelineSettingsPb_init_default, false, 0, false, _makesdr_AgcSpeed_MIN}
#define makesdr_TxPipelineSettingsPb_init_default {false, makesdr_PipelineSettingsPb_init_default}
#define makesdr_BasicBandSettingsPb_init_default {0, {""}, 0, {_makesdr_ModeType_MIN}, false, makesdr_BandRfSettingsPb_init_default, false, makesdr_IfSettingsPb_init_default, false, _makesdr_AgcSpeed_MIN}
#define makesdr_BasicIqBandSettingsPb_init_default {0, {""}, false, makesdr_BandRfSettingsPb_init_default, false, makesdr_IfSettingsPb_init_default, false, makesdr_RxPipelineSettingsPb_init_default}
#define makesdr_DualIqBandSettingsPb_init_default {0, {""}, false, makesdr_BandRfSettingsPb_init_default, false, makesdr_IfSettingsPb_init_default, _makesdr_PipelineId_MIN, false, makesdr_RxPipelineSettingsPb_init_default, false, makesdr_RxPipelineSettingsPb_init_default, false, 0, false, _makesdr_PipelineId_MIN}
#define makesdr_RxTxDualIqBandSettingsPb_init_default {0, {""}, false, makesdr_BandRfSettingsPb_init_default, false, makesdr_IfSettingsPb_init_default, _makesdr_PipelineId_MIN, false, makesdr_RxPipelineSettingsPb_init_default, false, makesdr_RxPipelineSettingsPb_init_default, false, 0, false, _makesdr_PipelineId_MIN, false, makesdr_TxPipelineSettingsPb_init_default, false, _makesdr_PipelineId_MIN}
#define makesdr_BasicActiveBandSettingsPb_init_default {false, makesdr_BasicBandSettingsPb_init_default}
#define makesdr_BasicIqActiveBandSettingsPb_init_default {false, makesdr_BasicIqBandSettingsPb_init_default}
#define makesdr_DualIqActiveBandSettingsPb_init_default {false, makesdr_DualIqBandSettingsPb_init_default}
#define makesdr_RxTxDualIqActiveBandSettingsPb_init_default {false, makesdr_RxTxDualIqBandSettingsPb_init_default}
#define makesdr_SplitBandDualIqActiveBandSettingsPb_init_default {_makesdr_SplitBandId_MIN, false, makesdr_RxTxDualIqBandSettingsPb_init_default, false, makesdr_RxTxDualIqBandSettingsPb_init_default, false, _makesdr_SplitBandId_MIN, false, _makesdr_SplitBandId_MIN, false, _makesdr_SplitBandId_MIN, false, 0}
#define makesdr_BasicBandSettingsCachePb_init_default {0, {makesdr_BasicBandSettingsCachePb_BandSettingsEntry_init_default, makesdr_BasicBandSettingsCachePb_BandSettingsEntry_init_default, makesdr_BasicBandSettingsCachePb_BandSettingsEntry_init_default, makesdr_BasicBandSettingsCachePb_BandSettingsEntry_init_default, makesdr_BasicBandSettingsCachePb_BandSettingsEntry_init_default, makesdr_BasicBandSettingsCachePb_BandSettingsEntry_init_default, makesdr_BasicBandSettingsCachePb_BandSettingsEntry_init_default, makesdr_BasicBandSettingsCachePb_BandSettingsEntry_init_default, makesdr_BasicBandSettingsCachePb_BandSettingsEntry_init_default, makesdr_BasicBandSettingsCachePb_BandSettingsEntry_init_default}}
#define makesdr_BasicBandSettingsCachePb_BandSettingsEntry_init_default {"", false, makesdr_BasicBandSettingsPb_init_default}
#define makesdr_BasicIqBandSettingsCachePb_init_default {0, {makesdr_BasicIqBandSettingsCachePb_BandSettingsEntry_init_default, makesdr_BasicIqBandSettingsCachePb_BandSettingsEntry_init_default, makesdr_BasicIqBandSettingsCachePb_BandSettingsEntry_init_default, makesdr_BasicIqBandSettingsCachePb_BandSettingsEntry_init_default, makesdr_BasicIqBandSettingsCachePb_BandSettingsEntry_init_default, makesdr_BasicIqBandSettingsCachePb_BandSettingsEntry_init_default, makesdr_BasicIqBandSettingsCachePb_BandSettingsEntry_init_default, makesdr_BasicIqBandSettingsCachePb_BandSettingsEntry_init_default, makesdr_BasicIqBandSettingsCachePb_BandSettingsEntry_init_default, makesdr_BasicIqBandSettingsCachePb_BandSettingsEntry_init_default}}
#define makesdr_BasicIqBandSettingsCachePb_BandSettingsEntry_init_default {"", false, makesdr_BasicIqBandSettingsPb_init_default}
#define makesdr_DualIqBandSettingsCachePb_init_default {0, {makesdr_DualIqBandSettingsCachePb_BandSettingsEntry_init_default, makesdr_DualIqBandSettingsCachePb_BandSettingsEntry_init_default, makesdr_DualIqBandSettingsCachePb_BandSettingsEntry_init_default, makesdr_DualIqBandSettingsCachePb_BandSettingsEntry_init_default, makesdr_DualIqBandSettingsCachePb_BandSettingsEntry_init_default, makesdr_DualIqBandSettingsCachePb_BandSettingsEntry_init_default, makesdr_DualIqBandSettingsCachePb_BandSettingsEntry_init_default, makesdr_DualIqBandSettingsCachePb_BandSettingsEntry_init_default, makesdr_DualIqBandSettingsCachePb_BandSettingsEntry_init_default, makesdr_DualIqBandSettingsCachePb_BandSettingsEntry_init_default}}
#define makesdr_DualIqBandSettingsCachePb_BandSettingsEntry_init_default {"", false, makesdr_DualIqBandSettingsPb_init_default}
#define makesdr_RxTxDualIqBandSettingsCachePb_init_default {0, {makesdr_RxTxDualIqBandSettingsCachePb_BandSettingsEntry_init_default, makesdr_RxTxDualIqBandSettingsCachePb_BandSettingsEntry_init_default, makesdr_RxTxDualIqBandSettingsCachePb_BandSettingsEntry_init_default, makesdr_RxTxDualIqBandSettingsCachePb_BandSettingsEntry_init_default, makesdr_RxTxDualIqBandSettingsCachePb_BandSettingsEntry_init_default, makesdr_RxTxDualIqBandSettingsCachePb_BandSettingsEntry_init_default, makesdr_RxTxDualIqBandSettingsCachePb_BandSettingsEntry_init_default, makesdr_RxTxDualIqBandSettingsCachePb_BandSettingsEntry_init_default, makesdr_RxTxDualIqBandSettingsCachePb_BandSettingsEntry_init_default, makesdr_RxTxDualIqBandSettingsCachePb_BandSettingsEntry_init_default}}
#define makesdr_RxTxDualIqBandSettingsCachePb_BandSettingsEntry_init_default {"", false, makesdr_RxTxDualIqBandSettingsPb_init_default}
#define makesdr_BasicRxSettingsPb_init_default   {false, makesdr_BasicActiveBandSettingsPb_init_default, false, makesdr_ReceiverSettingsPb_init_default, false, 0}
#define makesdr_BasicIqRxSettingsPb_init_default {false, makesdr_BasicIqActiveBandSettingsPb_init_default, false, makesdr_ReceiverSettingsPb_init_default, false, 0}
#define makesdr_DualIqRxSettingsPb_init_default  {false, makesdr_DualIqActiveBandSettingsPb_init_default, false, makesdr_ReceiverSettingsPb_init_default, false, 0}
#define makesdr_BasicRxTxSettingsPb_init_default {false, makesdr_BasicActiveBandSettingsPb_init_default, false, makesdr_ReceiverSettingsPb_init_default, false, makesdr_TransmitterSettingsPb_init_default, false, 0}
#define makesdr_BasicIqRxTxSettingsPb_init_default {false, makesdr_BasicIqActiveBandSettingsPb_init_default, false, makesdr_ReceiverSettingsPb_init_default, false, makesdr_TransmitterSettingsPb_init_default, false, 0}
#define makesdr_DualIqRxTxSettingsPb_init_default {false, makesdr_RxTxDualIqActiveBandSettingsPb_init_default, false, makesdr_ReceiverSettingsPb_init_default, false, makesdr_TransmitterSettingsPb_init_default, false, 0}
#define makesdr_SplitBandDualIqRxTxSettingsPb_init_default {false, makesdr_SplitBandDualIqActiveBandSettingsPb_init_default, false, makesdr_ReceiverSettingsPb_init_default, false, makesdr_TransmitterSettingsPb_init_default, false, 0}
#define makesdr_FieldUpdatePb_init_default       {0, {0, 0, 0, 0, 0, 0, 0, 0}, 0, {""}, _makesdr_FieldUpdateMeaning_MIN, 0, 0, 0}
#define makesdr_ModePb_init_zero                 {_makesdr_ModeType_MIN, "", "", 0, 0, 0}
#define makesdr_ModeListPb_init_zero             {0, {makesdr_ModePb_init_zero, makesdr_ModePb_init_zero, makesdr_ModePb_init_zero, makesdr_ModePb_init_zero, makesdr_ModePb_init_zero, makesdr_ModePb_init_zero, makesdr_ModePb_init_zero, makesdr_ModePb_init_zero, makesdr_ModePb_init_zero, makesdr_ModePb_init_zero}}
#define makesdr_BandPb_init_zero                 {"", "", 0, 0, 0, 0, 0, _makesdr_ModeType_MIN}
#define makesdr_BandListPb_init_zero             {0, {makesdr_BandPb_init_zero, makesdr_BandPb_init_zero, makesdr_BandPb_init_zero, makesdr_BandPb_init_zero, makesdr_BandPb_init_zero, makesdr_BandPb_init_zero, makesdr_BandPb_init_zero, makesdr_BandPb_init_zero, makesdr_BandPb_init_zero, makesdr_BandPb_init_zero, makesdr_BandPb_init_zero, makesdr_BandPb_init_zero, makesdr_BandPb_init_zero}}
#define makesdr_BandCategoryPb_init_zero         {"", "", false, makesdr_BandListPb_init_zero}
#define makesdr_BandCategoryListPb_init_zero     {0, {makesdr_BandCategoryPb_init_zero, makesdr_BandCategoryPb_init_zero, makesdr_BandCategoryPb_init_zero, makesdr_BandCategoryPb_init_zero, makesdr_BandCategoryPb_init_zero, makesdr_BandCategoryPb_init_zero, makesdr_BandCategoryPb_init_zero, makesdr_BandCategoryPb_init_zero}}
#define makesdr_RadioLookupPb_init_zero          {false, makesdr_BandCategoryListPb_init_zero, false, makesdr_ModeListPb_init_zero}
#define makesdr_SteppableInt64SettingPb_init_zero {0, 0, 0, 0}
#define makesdr_SteppableFloatSettingPb_init_zero {0, 0, 0, 0}
#define makesdr_IqCorrectionSettingsPb_init_zero {false, makesdr_SteppableFloatSettingPb_init_zero, false, makesdr_SteppableFloatSettingPb_init_zero}
#define makesdr_BandRfSettingsPb_init_zero       {false, makesdr_SteppableInt64SettingPb_init_zero, false, makesdr_SteppableFloatSettingPb_init_zero}
#define makesdr_PipelineRfSettingsPb_init_zero   {false, 0, false, 0, false, makesdr_SteppableInt64SettingPb_init_zero}
#define makesdr_IfSettingsPb_init_zero           {false, 0, false, makesdr_SteppableFloatSettingPb_init_zero}
#define makesdr_AfSettingsPb_init_zero           {false, makesdr_SteppableFloatSettingPb_init_zero}
#define makesdr_ReceiverSettingsPb_init_zero     {false, makesdr_AfSettingsPb_init_zero}
#define makesdr_TransmitterSettingsPb_init_zero  {false, makesdr_AfSettingsPb_init_zero}
#define makesdr_PipelineSettingsPb_init_zero     {0, {_makesdr_ModeType_MIN}, false, makesdr_PipelineRfSettingsPb_init_zero, false, makesdr_IqCorrectionSettingsPb_init_zero}
#define makesdr_RxPipelineSettingsPb_init_zero   {false, makesdr_PipelineSettingsPb_init_zero, false, 0, false, _makesdr_AgcSpeed_MIN}
#define makesdr_TxPipelineSettingsPb_init_zero   {false, makesdr_PipelineSettingsPb_init_zero}
#define makesdr_BasicBandSettingsPb_init_zero    {0, {""}, 0, {_makesdr_ModeType_MIN}, false, makesdr_BandRfSettingsPb_init_zero, false, makesdr_IfSettingsPb_init_zero, false, _makesdr_AgcSpeed_MIN}
#define makesdr_BasicIqBandSettingsPb_init_zero  {0, {""}, false, makesdr_BandRfSettingsPb_init_zero, false, makesdr_IfSettingsPb_init_zero, false, makesdr_RxPipelineSettingsPb_init_zero}
#define makesdr_DualIqBandSettingsPb_init_zero   {0, {""}, false, makesdr_BandRfSettingsPb_init_zero, false, makesdr_IfSettingsPb_init_zero, _makesdr_PipelineId_MIN, false, makesdr_RxPipelineSettingsPb_init_zero, false, makesdr_RxPipelineSettingsPb_init_zero, false, 0, false, _makesdr_PipelineId_MIN}
#define makesdr_RxTxDualIqBandSettingsPb_init_zero {0, {""}, false, makesdr_BandRfSettingsPb_init_zero, false, makesdr_IfSettingsPb_init_zero, _makesdr_PipelineId_MIN, false, makesdr_RxPipelineSettingsPb_init_zero, false, makesdr_RxPipelineSettingsPb_init_zero, false, 0, false, _makesdr_PipelineId_MIN, false, makesdr_TxPipelineSettingsPb_init_zero, false, _makesdr_PipelineId_MIN}
#define makesdr_BasicActiveBandSettingsPb_init_zero {false, makesdr_BasicBandSettingsPb_init_zero}
#define makesdr_BasicIqActiveBandSettingsPb_init_zero {false, makesdr_BasicIqBandSettingsPb_init_zero}
#define makesdr_DualIqActiveBandSettingsPb_init_zero {false, makesdr_DualIqBandSettingsPb_init_zero}
#define makesdr_RxTxDualIqActiveBandSettingsPb_init_zero {false, makesdr_RxTxDualIqBandSettingsPb_init_zero}
#define makesdr_SplitBandDualIqActiveBandSettingsPb_init_zero {_makesdr_SplitBandId_MIN, false, makesdr_RxTxDualIqBandSettingsPb_init_zero, false, makesdr_RxTxDualIqBandSettingsPb_init_zero, false, _makesdr_SplitBandId_MIN, false, _makesdr_SplitBandId_MIN, false, _makesdr_SplitBandId_MIN, false, 0}
#define makesdr_BasicBandSettingsCachePb_init_zero {0, {makesdr_BasicBandSettingsCachePb_BandSettingsEntry_init_zero, makesdr_BasicBandSettingsCachePb_BandSettingsEntry_init_zero, makesdr_BasicBandSettingsCachePb_BandSettingsEntry_init_zero, makesdr_BasicBandSettingsCachePb_BandSettingsEntry_init_zero, makesdr_BasicBandSettingsCachePb_BandSettingsEntry_init_zero, makesdr_BasicBandSettingsCachePb_BandSettingsEntry_init_zero, makesdr_BasicBandSettingsCachePb_BandSettingsEntry_init_zero, makesdr_BasicBandSettingsCachePb_BandSettingsEntry_init_zero, makesdr_BasicBandSettingsCachePb_BandSettingsEntry_init_zero, makesdr_BasicBandSettingsCachePb_BandSettingsEntry_init_zero}}
#define makesdr_BasicBandSettingsCachePb_BandSettingsEntry_init_zero {"", false, makesdr_BasicBandSettingsPb_init_zero}
#define makesdr_BasicIqBandSettingsCachePb_init_zero {0, {makesdr_BasicIqBandSettingsCachePb_BandSettingsEntry_init_zero, makesdr_BasicIqBandSettingsCachePb_BandSettingsEntry_init_zero, makesdr_BasicIqBandSettingsCachePb_BandSettingsEntry_init_zero, makesdr_BasicIqBandSettingsCachePb_BandSettingsEntry_init_zero, makesdr_BasicIqBandSettingsCachePb_BandSettingsEntry_init_zero, makesdr_BasicIqBandSettingsCachePb_BandSettingsEntry_init_zero, makesdr_BasicIqBandSettingsCachePb_BandSettingsEntry_init_zero, makesdr_BasicIqBandSettingsCachePb_BandSettingsEntry_init_zero, makesdr_BasicIqBandSettingsCachePb_BandSettingsEntry_init_zero, makesdr_BasicIqBandSettingsCachePb_BandSettingsEntry_init_zero}}
#define makesdr_BasicIqBandSettingsCachePb_BandSettingsEntry_init_zero {"", false, makesdr_BasicIqBandSettingsPb_init_zero}
#define makesdr_DualIqBandSettingsCachePb_init_zero {0, {makesdr_DualIqBandSettingsCachePb_BandSettingsEntry_init_zero, makesdr_DualIqBandSettingsCachePb_BandSettingsEntry_init_zero, makesdr_DualIqBandSettingsCachePb_BandSettingsEntry_init_zero, makesdr_DualIqBandSettingsCachePb_BandSettingsEntry_init_zero, makesdr_DualIqBandSettingsCachePb_BandSettingsEntry_init_zero, makesdr_DualIqBandSettingsCachePb_BandSettingsEntry_init_zero, makesdr_DualIqBandSettingsCachePb_BandSettingsEntry_init_zero, makesdr_DualIqBandSettingsCachePb_BandSettingsEntry_init_zero, makesdr_DualIqBandSettingsCachePb_BandSettingsEntry_init_zero, makesdr_DualIqBandSettingsCachePb_BandSettingsEntry_init_zero}}
#define makesdr_DualIqBandSettingsCachePb_BandSettingsEntry_init_zero {"", false, makesdr_DualIqBandSettingsPb_init_zero}
#define makesdr_RxTxDualIqBandSettingsCachePb_init_zero {0, {makesdr_RxTxDualIqBandSettingsCachePb_BandSettingsEntry_init_zero, makesdr_RxTxDualIqBandSettingsCachePb_BandSettingsEntry_init_zero, makesdr_RxTxDualIqBandSettingsCachePb_BandSettingsEntry_init_zero, makesdr_RxTxDualIqBandSettingsCachePb_BandSettingsEntry_init_zero, makesdr_RxTxDualIqBandSettingsCachePb_BandSettingsEntry_init_zero, makesdr_RxTxDualIqBandSettingsCachePb_BandSettingsEntry_init_zero, makesdr_RxTxDualIqBandSettingsCachePb_BandSettingsEntry_init_zero, makesdr_RxTxDualIqBandSettingsCachePb_BandSettingsEntry_init_zero, makesdr_RxTxDualIqBandSettingsCachePb_BandSettingsEntry_init_zero, makesdr_RxTxDualIqBandSettingsCachePb_BandSettingsEntry_init_zero}}
#define makesdr_RxTxDualIqBandSettingsCachePb_BandSettingsEntry_init_zero {"", false, makesdr_RxTxDualIqBandSettingsPb_init_zero}
#define makesdr_BasicRxSettingsPb_init_zero      {false, makesdr_BasicActiveBandSettingsPb_init_zero, false, makesdr_ReceiverSettingsPb_init_zero, false, 0}
#define makesdr_BasicIqRxSettingsPb_init_zero    {false, makesdr_BasicIqActiveBandSettingsPb_init_zero, false, makesdr_ReceiverSettingsPb_init_zero, false, 0}
#define makesdr_DualIqRxSettingsPb_init_zero     {false, makesdr_DualIqActiveBandSettingsPb_init_zero, false, makesdr_ReceiverSettingsPb_init_zero, false, 0}
#define makesdr_BasicRxTxSettingsPb_init_zero    {false, makesdr_BasicActiveBandSettingsPb_init_zero, false, makesdr_ReceiverSettingsPb_init_zero, false, makesdr_TransmitterSettingsPb_init_zero, false, 0}
#define makesdr_BasicIqRxTxSettingsPb_init_zero  {false, makesdr_BasicIqActiveBandSettingsPb_init_zero, false, makesdr_ReceiverSettingsPb_init_zero, false, makesdr_TransmitterSettingsPb_init_zero, false, 0}
#define makesdr_DualIqRxTxSettingsPb_init_zero   {false, makesdr_RxTxDualIqActiveBandSettingsPb_init_zero, false, makesdr_ReceiverSettingsPb_init_zero, false, makesdr_TransmitterSettingsPb_init_zero, false, 0}
#define makesdr_SplitBandDualIqRxTxSettingsPb_init_zero {false, makesdr_SplitBandDualIqActiveBandSettingsPb_init_zero, false, makesdr_ReceiverSettingsPb_init_zero, false, makesdr_TransmitterSettingsPb_init_zero, false, 0}
#define makesdr_FieldUpdatePb_init_zero          {0, {0, 0, 0, 0, 0, 0, 0, 0}, 0, {""}, _makesdr_FieldUpdateMeaning_MIN, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define makesdr_ModePb_type_tag                  1
#define makesdr_ModePb_name_tag                  2
#define makesdr_ModePb_label_tag                 3
#define makesdr_ModePb_lo_cut_tag                4
#define makesdr_ModePb_hi_cut_tag                5
#define makesdr_ModePb_offset_tag                6
#define makesdr_ModeListPb_modes_tag             1
#define makesdr_BandPb_name_tag                  1
#define makesdr_BandPb_label_tag                 2
#define makesdr_BandPb_lowest_frequency_tag      3
#define makesdr_BandPb_highest_frequency_tag     4
#define makesdr_BandPb_landing_frequency_tag     5
#define makesdr_BandPb_default_fine_step_tag     6
#define makesdr_BandPb_default_coarse_step_tag   7
#define makesdr_BandPb_default_mode_tag          8
#define makesdr_BandListPb_bands_tag             1
#define makesdr_BandCategoryPb_name_tag          1
#define makesdr_BandCategoryPb_label_tag         2
#define makesdr_BandCategoryPb_bands_tag         3
#define makesdr_BandCategoryListPb_categories_tag 1
#define makesdr_RadioLookupPb_bands_tag          1
#define makesdr_RadioLookupPb_modes_tag          2
#define makesdr_SteppableInt64SettingPb_value_tag 1
#define makesdr_SteppableInt64SettingPb_coarse_delta_tag 2
#define makesdr_SteppableInt64SettingPb_fine_delta_tag 3
#define makesdr_SteppableInt64SettingPb_use_fine_tag 4
#define makesdr_SteppableFloatSettingPb_value_tag 1
#define makesdr_SteppableFloatSettingPb_coarse_delta_tag 2
#define makesdr_SteppableFloatSettingPb_fine_delta_tag 3
#define makesdr_SteppableFloatSettingPb_use_fine_tag 4
#define makesdr_IqCorrectionSettingsPb_amplitude_tag 1001
#define makesdr_IqCorrectionSettingsPb_phase_tag 1002
#define makesdr_BandRfSettingsPb_frequency_tag   1001
#define makesdr_BandRfSettingsPb_gain_tag        1002
#define makesdr_PipelineRfSettingsPb_max_negative_offset_tag 4
#define makesdr_PipelineRfSettingsPb_max_positive_offset_tag 5
#define makesdr_PipelineRfSettingsPb_frequency_tag 1001
#define makesdr_IfSettingsPb_bandwidth_tag       2
#define makesdr_IfSettingsPb_gain_tag            1001
#define makesdr_AfSettingsPb_gain_tag            1001
#define makesdr_ReceiverSettingsPb_volume_tag    2
#define makesdr_TransmitterSettingsPb_mic_tag    2
#define makesdr_PipelineSettingsPb_mode_request_tag 1
#define makesdr_PipelineSettingsPb_mode_tag      2
#define makesdr_PipelineSettingsPb_rf_tag        3
#define makesdr_PipelineSettingsPb_iq_corrections_tag 4
#define makesdr_RxPipelineSettingsPb_base_tag    1
#define makesdr_RxPipelineSettingsPb_mute_tag    2
#define makesdr_RxPipelineSettingsPb_agc_speed_tag 3
#define makesdr_TxPipelineSettingsPb_base_tag    1
#define makesdr_BasicBandSettingsPb_band_request_tag 1
#define makesdr_BasicBandSettingsPb_band_tag     2
#define makesdr_BasicBandSettingsPb_mode_request_tag 3
#define makesdr_BasicBandSettingsPb_mode_tag     4
#define makesdr_BasicBandSettingsPb_rf_tag       5
#define makesdr_BasicBandSettingsPb_if_tag       6
#define makesdr_BasicBandSettingsPb_agc_speed_tag 7
#define makesdr_BasicIqBandSettingsPb_band_request_tag 1
#define makesdr_BasicIqBandSettingsPb_band_tag   2
#define makesdr_BasicIqBandSettingsPb_rf_tag     5
#define makesdr_BasicIqBandSettingsPb_if_tag     6
#define makesdr_BasicIqBandSettingsPb_focus_pipeline_tag 10
#define makesdr_DualIqBandSettingsPb_band_request_tag 1
#define makesdr_DualIqBandSettingsPb_band_tag    2
#define makesdr_DualIqBandSettingsPb_rf_tag      5
#define makesdr_DualIqBandSettingsPb_if_tag      6
#define makesdr_DualIqBandSettingsPb_focus_pipeline_tag 10
#define makesdr_DualIqBandSettingsPb_pipeline_a_tag 11
#define makesdr_DualIqBandSettingsPb_pipeline_b_tag 12
#define makesdr_DualIqBandSettingsPb_is_multi_pipeline_tag 13
#define makesdr_DualIqBandSettingsPb_focus_pipeline_id_tag 14
#define makesdr_RxTxDualIqBandSettingsPb_band_request_tag 1
#define makesdr_RxTxDualIqBandSettingsPb_band_tag 2
#define makesdr_RxTxDualIqBandSettingsPb_rf_tag  5
#define makesdr_RxTxDualIqBandSettingsPb_if_tag  6
#define makesdr_RxTxDualIqBandSettingsPb_focus_pipeline_tag 10
#define makesdr_RxTxDualIqBandSettingsPb_pipeline_a_tag 11
#define makesdr_RxTxDualIqBandSettingsPb_pipeline_b_tag 12
#define makesdr_RxTxDualIqBandSettingsPb_is_multi_pipeline_tag 13
#define makesdr_RxTxDualIqBandSettingsPb_focus_pipeline_id_tag 14
#define makesdr_RxTxDualIqBandSettingsPb_tx_pipeline_tag 15
#define makesdr_RxTxDualIqBandSettingsPb_tx_pipeline_id_tag 16
#define makesdr_BasicActiveBandSettingsPb_focus_band_tag 1
#define makesdr_BasicIqActiveBandSettingsPb_focus_band_tag 1
#define makesdr_DualIqActiveBandSettingsPb_focus_band_tag 1
#define makesdr_RxTxDualIqActiveBandSettingsPb_focus_band_tag 1
#define makesdr_SplitBandDualIqActiveBandSettingsPb_focus_band_tag 1
#define makesdr_SplitBandDualIqActiveBandSettingsPb_band_1_tag 2
#define makesdr_SplitBandDualIqActiveBandSettingsPb_band_2_tag 3
#define makesdr_SplitBandDualIqActiveBandSettingsPb_focus_band_id_tag 4
#define makesdr_SplitBandDualIqActiveBandSettingsPb_tx_band_id_tag 5
#define makesdr_SplitBandDualIqActiveBandSettingsPb_rx_band_id_tag 6
#define makesdr_SplitBandDualIqActiveBandSettingsPb_is_split_tag 7
#define makesdr_BasicBandSettingsCachePb_BandSettingsEntry_key_tag 1
#define makesdr_BasicBandSettingsCachePb_BandSettingsEntry_value_tag 2
#define makesdr_BasicBandSettingsCachePb_band_settings_tag 1
#define makesdr_BasicIqBandSettingsCachePb_BandSettingsEntry_key_tag 1
#define makesdr_BasicIqBandSettingsCachePb_BandSettingsEntry_value_tag 2
#define makesdr_BasicIqBandSettingsCachePb_band_settings_tag 1
#define makesdr_DualIqBandSettingsCachePb_BandSettingsEntry_key_tag 1
#define makesdr_DualIqBandSettingsCachePb_BandSettingsEntry_value_tag 2
#define makesdr_DualIqBandSettingsCachePb_band_settings_tag 1
#define makesdr_RxTxDualIqBandSettingsCachePb_BandSettingsEntry_key_tag 1
#define makesdr_RxTxDualIqBandSettingsCachePb_BandSettingsEntry_value_tag 2
#define makesdr_RxTxDualIqBandSettingsCachePb_band_settings_tag 1
#define makesdr_BasicRxSettingsPb_active_bands_tag 1
#define makesdr_BasicRxSettingsPb_receiver_tag   2
#define makesdr_BasicRxSettingsPb_ptt_tag        4
#define makesdr_BasicIqRxSettingsPb_active_bands_tag 1
#define makesdr_BasicIqRxSettingsPb_receiver_tag 2
#define makesdr_BasicIqRxSettingsPb_ptt_tag      4
#define makesdr_DualIqRxSettingsPb_active_bands_tag 1
#define makesdr_DualIqRxSettingsPb_receiver_tag  2
#define makesdr_DualIqRxSettingsPb_ptt_tag       4
#define makesdr_BasicRxTxSettingsPb_active_bands_tag 1
#define makesdr_BasicRxTxSettingsPb_receiver_tag 2
#define makesdr_BasicRxTxSettingsPb_transmitter_tag 3
#define makesdr_BasicRxTxSettingsPb_ptt_tag      4
#define makesdr_BasicIqRxTxSettingsPb_active_bands_tag 1
#define makesdr_BasicIqRxTxSettingsPb_receiver_tag 2
#define makesdr_BasicIqRxTxSettingsPb_transmitter_tag 3
#define makesdr_BasicIqRxTxSettingsPb_ptt_tag    4
#define makesdr_DualIqRxTxSettingsPb_active_bands_tag 1
#define makesdr_DualIqRxTxSettingsPb_receiver_tag 2
#define makesdr_DualIqRxTxSettingsPb_transmitter_tag 3
#define makesdr_DualIqRxTxSettingsPb_ptt_tag     4
#define makesdr_SplitBandDualIqRxTxSettingsPb_active_bands_tag 1
#define makesdr_SplitBandDualIqRxTxSettingsPb_receiver_tag 2
#define makesdr_SplitBandDualIqRxTxSettingsPb_transmitter_tag 3
#define makesdr_SplitBandDualIqRxTxSettingsPb_ptt_tag 4
#define makesdr_FieldUpdatePb_path_tag           1
#define makesdr_FieldUpdatePb_string_value_tag   2
#define makesdr_FieldUpdatePb_int32_value_tag    3
#define makesdr_FieldUpdatePb_uint32_value_tag   4
#define makesdr_FieldUpdatePb_int64_value_tag    5
#define makesdr_FieldUpdatePb_float_value_tag    6
#define makesdr_FieldUpdatePb_bool_value_tag     7
#define makesdr_FieldUpdatePb_meaning_tag        10
#define makesdr_FieldUpdatePb_is_indirect_tag    11
#define makesdr_FieldUpdatePb_is_auto_complete_tag 12
#define makesdr_FieldUpdatePb_is_final_tag       13

/* Struct field encoding specification for nanopb */
#define makesdr_ModePb_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, STRING,   name,              2) \
X(a, STATIC,   SINGULAR, STRING,   label,             3) \
X(a, STATIC,   SINGULAR, INT32,    lo_cut,            4) \
X(a, STATIC,   SINGULAR, INT32,    hi_cut,            5) \
X(a, STATIC,   SINGULAR, INT32,    offset,            6)
#define makesdr_ModePb_CALLBACK NULL
#define makesdr_ModePb_DEFAULT NULL

#define makesdr_ModeListPb_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  modes,             1)
#define makesdr_ModeListPb_CALLBACK NULL
#define makesdr_ModeListPb_DEFAULT NULL
#define makesdr_ModeListPb_modes_MSGTYPE makesdr_ModePb

#define makesdr_BandPb_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, STRING,   label,             2) \
X(a, STATIC,   SINGULAR, INT64,    lowest_frequency,   3) \
X(a, STATIC,   SINGULAR, INT64,    highest_frequency,   4) \
X(a, STATIC,   SINGULAR, INT64,    landing_frequency,   5) \
X(a, STATIC,   SINGULAR, INT32,    default_fine_step,   6) \
X(a, STATIC,   SINGULAR, INT32,    default_coarse_step,   7) \
X(a, STATIC,   SINGULAR, UENUM,    default_mode,      8)
#define makesdr_BandPb_CALLBACK NULL
#define makesdr_BandPb_DEFAULT NULL

#define makesdr_BandListPb_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  bands,             1)
#define makesdr_BandListPb_CALLBACK NULL
#define makesdr_BandListPb_DEFAULT NULL
#define makesdr_BandListPb_bands_MSGTYPE makesdr_BandPb

#define makesdr_BandCategoryPb_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, STRING,   label,             2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  bands,             3)
#define makesdr_BandCategoryPb_CALLBACK NULL
#define makesdr_BandCategoryPb_DEFAULT NULL
#define makesdr_BandCategoryPb_bands_MSGTYPE makesdr_BandListPb

#define makesdr_BandCategoryListPb_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  categories,        1)
#define makesdr_BandCategoryListPb_CALLBACK NULL
#define makesdr_BandCategoryListPb_DEFAULT NULL
#define makesdr_BandCategoryListPb_categories_MSGTYPE makesdr_BandCategoryPb

#define makesdr_RadioLookupPb_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  bands,             1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  modes,             2)
#define makesdr_RadioLookupPb_CALLBACK NULL
#define makesdr_RadioLookupPb_DEFAULT NULL
#define makesdr_RadioLookupPb_bands_MSGTYPE makesdr_BandCategoryListPb
#define makesdr_RadioLookupPb_modes_MSGTYPE makesdr_ModeListPb

#define makesdr_SteppableInt64SettingPb_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    value,             1) \
X(a, STATIC,   SINGULAR, INT64,    coarse_delta,      2) \
X(a, STATIC,   SINGULAR, INT64,    fine_delta,        3) \
X(a, STATIC,   SINGULAR, BOOL,     use_fine,          4)
#define makesdr_SteppableInt64SettingPb_CALLBACK NULL
#define makesdr_SteppableInt64SettingPb_DEFAULT NULL

#define makesdr_SteppableFloatSettingPb_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    value,             1) \
X(a, STATIC,   SINGULAR, FLOAT,    coarse_delta,      2) \
X(a, STATIC,   SINGULAR, FLOAT,    fine_delta,        3) \
X(a, STATIC,   SINGULAR, BOOL,     use_fine,          4)
#define makesdr_SteppableFloatSettingPb_CALLBACK NULL
#define makesdr_SteppableFloatSettingPb_DEFAULT NULL

#define makesdr_IqCorrectionSettingsPb_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  amplitude,       1001) \
X(a, STATIC,   OPTIONAL, MESSAGE,  phase,           1002)
#define makesdr_IqCorrectionSettingsPb_CALLBACK NULL
#define makesdr_IqCorrectionSettingsPb_DEFAULT NULL
#define makesdr_IqCorrectionSettingsPb_amplitude_MSGTYPE makesdr_SteppableFloatSettingPb
#define makesdr_IqCorrectionSettingsPb_phase_MSGTYPE makesdr_SteppableFloatSettingPb

#define makesdr_BandRfSettingsPb_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  frequency,       1001) \
X(a, STATIC,   OPTIONAL, MESSAGE,  gain,            1002)
#define makesdr_BandRfSettingsPb_CALLBACK NULL
#define makesdr_BandRfSettingsPb_DEFAULT NULL
#define makesdr_BandRfSettingsPb_frequency_MSGTYPE makesdr_SteppableInt64SettingPb
#define makesdr_BandRfSettingsPb_gain_MSGTYPE makesdr_SteppableFloatSettingPb

#define makesdr_PipelineRfSettingsPb_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    max_negative_offset,   4) \
X(a, STATIC,   OPTIONAL, INT32,    max_positive_offset,   5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  frequency,       1001)
#define makesdr_PipelineRfSettingsPb_CALLBACK NULL
#define makesdr_PipelineRfSettingsPb_DEFAULT NULL
#define makesdr_PipelineRfSettingsPb_frequency_MSGTYPE makesdr_SteppableInt64SettingPb

#define makesdr_IfSettingsPb_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   bandwidth,         2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  gain,            1001)
#define makesdr_IfSettingsPb_CALLBACK NULL
#define makesdr_IfSettingsPb_DEFAULT NULL
#define makesdr_IfSettingsPb_gain_MSGTYPE makesdr_SteppableFloatSettingPb

#define makesdr_AfSettingsPb_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  gain,            1001)
#define makesdr_AfSettingsPb_CALLBACK NULL
#define makesdr_AfSettingsPb_DEFAULT NULL
#define makesdr_AfSettingsPb_gain_MSGTYPE makesdr_SteppableFloatSettingPb

#define makesdr_ReceiverSettingsPb_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  volume,            2)
#define makesdr_ReceiverSettingsPb_CALLBACK NULL
#define makesdr_ReceiverSettingsPb_DEFAULT NULL
#define makesdr_ReceiverSettingsPb_volume_MSGTYPE makesdr_AfSettingsPb

#define makesdr_TransmitterSettingsPb_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  mic,               2)
#define makesdr_TransmitterSettingsPb_CALLBACK NULL
#define makesdr_TransmitterSettingsPb_DEFAULT NULL
#define makesdr_TransmitterSettingsPb_mic_MSGTYPE makesdr_AfSettingsPb

#define makesdr_PipelineSettingsPb_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    UENUM,    (mode_or_request,mode_request,mode_or_request.mode_request),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (mode_or_request,mode,mode_or_request.mode),   2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  rf,                3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  iq_corrections,    4)
#define makesdr_PipelineSettingsPb_CALLBACK NULL
#define makesdr_PipelineSettingsPb_DEFAULT NULL
#define makesdr_PipelineSettingsPb_mode_or_request_mode_MSGTYPE makesdr_ModePb
#define makesdr_PipelineSettingsPb_rf_MSGTYPE makesdr_PipelineRfSettingsPb
#define makesdr_PipelineSettingsPb_iq_corrections_MSGTYPE makesdr_IqCorrectionSettingsPb

#define makesdr_RxPipelineSettingsPb_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  base,              1) \
X(a, STATIC,   OPTIONAL, BOOL,     mute,              2) \
X(a, STATIC,   OPTIONAL, UENUM,    agc_speed,         3)
#define makesdr_RxPipelineSettingsPb_CALLBACK NULL
#define makesdr_RxPipelineSettingsPb_DEFAULT NULL
#define makesdr_RxPipelineSettingsPb_base_MSGTYPE makesdr_PipelineSettingsPb

#define makesdr_TxPipelineSettingsPb_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  base,              1)
#define makesdr_TxPipelineSettingsPb_CALLBACK NULL
#define makesdr_TxPipelineSettingsPb_DEFAULT NULL
#define makesdr_TxPipelineSettingsPb_base_MSGTYPE makesdr_PipelineSettingsPb

#define makesdr_BasicBandSettingsPb_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    STRING,   (band_or_request,band_request,band_or_request.band_request),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (band_or_request,band,band_or_request.band),   2) \
X(a, STATIC,   ONEOF,    UENUM,    (mode_or_request,mode_request,mode_or_request.mode_request),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (mode_or_request,mode,mode_or_request.mode),   4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  rf,                5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  if_,               6) \
X(a, STATIC,   OPTIONAL, UENUM,    agc_speed,         7)
#define makesdr_BasicBandSettingsPb_CALLBACK NULL
#define makesdr_BasicBandSettingsPb_DEFAULT NULL
#define makesdr_BasicBandSettingsPb_band_or_request_band_MSGTYPE makesdr_BandPb
#define makesdr_BasicBandSettingsPb_mode_or_request_mode_MSGTYPE makesdr_ModePb
#define makesdr_BasicBandSettingsPb_rf_MSGTYPE makesdr_BandRfSettingsPb
#define makesdr_BasicBandSettingsPb_if__MSGTYPE makesdr_IfSettingsPb

#define makesdr_BasicIqBandSettingsPb_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    STRING,   (band_or_request,band_request,band_or_request.band_request),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (band_or_request,band,band_or_request.band),   2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  rf,                5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  if_,               6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  focus_pipeline,   10)
#define makesdr_BasicIqBandSettingsPb_CALLBACK NULL
#define makesdr_BasicIqBandSettingsPb_DEFAULT NULL
#define makesdr_BasicIqBandSettingsPb_band_or_request_band_MSGTYPE makesdr_BandPb
#define makesdr_BasicIqBandSettingsPb_rf_MSGTYPE makesdr_BandRfSettingsPb
#define makesdr_BasicIqBandSettingsPb_if__MSGTYPE makesdr_IfSettingsPb
#define makesdr_BasicIqBandSettingsPb_focus_pipeline_MSGTYPE makesdr_RxPipelineSettingsPb

#define makesdr_DualIqBandSettingsPb_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    STRING,   (band_or_request,band_request,band_or_request.band_request),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (band_or_request,band,band_or_request.band),   2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  rf,                5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  if_,               6) \
X(a, STATIC,   SINGULAR, UENUM,    focus_pipeline,   10) \
X(a, STATIC,   OPTIONAL, MESSAGE,  pipeline_a,       11) \
X(a, STATIC,   OPTIONAL, MESSAGE,  pipeline_b,       12) \
X(a, STATIC,   OPTIONAL, BOOL,     is_multi_pipeline,  13) \
X(a, STATIC,   OPTIONAL, UENUM,    focus_pipeline_id,  14)
#define makesdr_DualIqBandSettingsPb_CALLBACK NULL
#define makesdr_DualIqBandSettingsPb_DEFAULT NULL
#define makesdr_DualIqBandSettingsPb_band_or_request_band_MSGTYPE makesdr_BandPb
#define makesdr_DualIqBandSettingsPb_rf_MSGTYPE makesdr_BandRfSettingsPb
#define makesdr_DualIqBandSettingsPb_if__MSGTYPE makesdr_IfSettingsPb
#define makesdr_DualIqBandSettingsPb_pipeline_a_MSGTYPE makesdr_RxPipelineSettingsPb
#define makesdr_DualIqBandSettingsPb_pipeline_b_MSGTYPE makesdr_RxPipelineSettingsPb

#define makesdr_RxTxDualIqBandSettingsPb_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    STRING,   (band_or_request,band_request,band_or_request.band_request),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (band_or_request,band,band_or_request.band),   2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  rf,                5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  if_,               6) \
X(a, STATIC,   SINGULAR, UENUM,    focus_pipeline,   10) \
X(a, STATIC,   OPTIONAL, MESSAGE,  pipeline_a,       11) \
X(a, STATIC,   OPTIONAL, MESSAGE,  pipeline_b,       12) \
X(a, STATIC,   OPTIONAL, BOOL,     is_multi_pipeline,  13) \
X(a, STATIC,   OPTIONAL, UENUM,    focus_pipeline_id,  14) \
X(a, STATIC,   OPTIONAL, MESSAGE,  tx_pipeline,      15) \
X(a, STATIC,   OPTIONAL, UENUM,    tx_pipeline_id,   16)
#define makesdr_RxTxDualIqBandSettingsPb_CALLBACK NULL
#define makesdr_RxTxDualIqBandSettingsPb_DEFAULT NULL
#define makesdr_RxTxDualIqBandSettingsPb_band_or_request_band_MSGTYPE makesdr_BandPb
#define makesdr_RxTxDualIqBandSettingsPb_rf_MSGTYPE makesdr_BandRfSettingsPb
#define makesdr_RxTxDualIqBandSettingsPb_if__MSGTYPE makesdr_IfSettingsPb
#define makesdr_RxTxDualIqBandSettingsPb_pipeline_a_MSGTYPE makesdr_RxPipelineSettingsPb
#define makesdr_RxTxDualIqBandSettingsPb_pipeline_b_MSGTYPE makesdr_RxPipelineSettingsPb
#define makesdr_RxTxDualIqBandSettingsPb_tx_pipeline_MSGTYPE makesdr_TxPipelineSettingsPb

#define makesdr_BasicActiveBandSettingsPb_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  focus_band,        1)
#define makesdr_BasicActiveBandSettingsPb_CALLBACK NULL
#define makesdr_BasicActiveBandSettingsPb_DEFAULT NULL
#define makesdr_BasicActiveBandSettingsPb_focus_band_MSGTYPE makesdr_BasicBandSettingsPb

#define makesdr_BasicIqActiveBandSettingsPb_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  focus_band,        1)
#define makesdr_BasicIqActiveBandSettingsPb_CALLBACK NULL
#define makesdr_BasicIqActiveBandSettingsPb_DEFAULT NULL
#define makesdr_BasicIqActiveBandSettingsPb_focus_band_MSGTYPE makesdr_BasicIqBandSettingsPb

#define makesdr_DualIqActiveBandSettingsPb_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  focus_band,        1)
#define makesdr_DualIqActiveBandSettingsPb_CALLBACK NULL
#define makesdr_DualIqActiveBandSettingsPb_DEFAULT NULL
#define makesdr_DualIqActiveBandSettingsPb_focus_band_MSGTYPE makesdr_DualIqBandSettingsPb

#define makesdr_RxTxDualIqActiveBandSettingsPb_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  focus_band,        1)
#define makesdr_RxTxDualIqActiveBandSettingsPb_CALLBACK NULL
#define makesdr_RxTxDualIqActiveBandSettingsPb_DEFAULT NULL
#define makesdr_RxTxDualIqActiveBandSettingsPb_focus_band_MSGTYPE makesdr_RxTxDualIqBandSettingsPb

#define makesdr_SplitBandDualIqActiveBandSettingsPb_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    focus_band,        1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  band_1,            2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  band_2,            3) \
X(a, STATIC,   OPTIONAL, UENUM,    focus_band_id,     4) \
X(a, STATIC,   OPTIONAL, UENUM,    tx_band_id,        5) \
X(a, STATIC,   OPTIONAL, UENUM,    rx_band_id,        6) \
X(a, STATIC,   OPTIONAL, BOOL,     is_split,          7)
#define makesdr_SplitBandDualIqActiveBandSettingsPb_CALLBACK NULL
#define makesdr_SplitBandDualIqActiveBandSettingsPb_DEFAULT NULL
#define makesdr_SplitBandDualIqActiveBandSettingsPb_band_1_MSGTYPE makesdr_RxTxDualIqBandSettingsPb
#define makesdr_SplitBandDualIqActiveBandSettingsPb_band_2_MSGTYPE makesdr_RxTxDualIqBandSettingsPb

#define makesdr_BasicBandSettingsCachePb_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  band_settings,     1)
#define makesdr_BasicBandSettingsCachePb_CALLBACK NULL
#define makesdr_BasicBandSettingsCachePb_DEFAULT NULL
#define makesdr_BasicBandSettingsCachePb_band_settings_MSGTYPE makesdr_BasicBandSettingsCachePb_BandSettingsEntry

#define makesdr_BasicBandSettingsCachePb_BandSettingsEntry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define makesdr_BasicBandSettingsCachePb_BandSettingsEntry_CALLBACK NULL
#define makesdr_BasicBandSettingsCachePb_BandSettingsEntry_DEFAULT NULL
#define makesdr_BasicBandSettingsCachePb_BandSettingsEntry_value_MSGTYPE makesdr_BasicBandSettingsPb

#define makesdr_BasicIqBandSettingsCachePb_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  band_settings,     1)
#define makesdr_BasicIqBandSettingsCachePb_CALLBACK NULL
#define makesdr_BasicIqBandSettingsCachePb_DEFAULT NULL
#define makesdr_BasicIqBandSettingsCachePb_band_settings_MSGTYPE makesdr_BasicIqBandSettingsCachePb_BandSettingsEntry

#define makesdr_BasicIqBandSettingsCachePb_BandSettingsEntry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define makesdr_BasicIqBandSettingsCachePb_BandSettingsEntry_CALLBACK NULL
#define makesdr_BasicIqBandSettingsCachePb_BandSettingsEntry_DEFAULT NULL
#define makesdr_BasicIqBandSettingsCachePb_BandSettingsEntry_value_MSGTYPE makesdr_BasicIqBandSettingsPb

#define makesdr_DualIqBandSettingsCachePb_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  band_settings,     1)
#define makesdr_DualIqBandSettingsCachePb_CALLBACK NULL
#define makesdr_DualIqBandSettingsCachePb_DEFAULT NULL
#define makesdr_DualIqBandSettingsCachePb_band_settings_MSGTYPE makesdr_DualIqBandSettingsCachePb_BandSettingsEntry

#define makesdr_DualIqBandSettingsCachePb_BandSettingsEntry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define makesdr_DualIqBandSettingsCachePb_BandSettingsEntry_CALLBACK NULL
#define makesdr_DualIqBandSettingsCachePb_BandSettingsEntry_DEFAULT NULL
#define makesdr_DualIqBandSettingsCachePb_BandSettingsEntry_value_MSGTYPE makesdr_DualIqBandSettingsPb

#define makesdr_RxTxDualIqBandSettingsCachePb_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  band_settings,     1)
#define makesdr_RxTxDualIqBandSettingsCachePb_CALLBACK NULL
#define makesdr_RxTxDualIqBandSettingsCachePb_DEFAULT NULL
#define makesdr_RxTxDualIqBandSettingsCachePb_band_settings_MSGTYPE makesdr_RxTxDualIqBandSettingsCachePb_BandSettingsEntry

#define makesdr_RxTxDualIqBandSettingsCachePb_BandSettingsEntry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define makesdr_RxTxDualIqBandSettingsCachePb_BandSettingsEntry_CALLBACK NULL
#define makesdr_RxTxDualIqBandSettingsCachePb_BandSettingsEntry_DEFAULT NULL
#define makesdr_RxTxDualIqBandSettingsCachePb_BandSettingsEntry_value_MSGTYPE makesdr_RxTxDualIqBandSettingsPb

#define makesdr_BasicRxSettingsPb_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  active_bands,      1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  receiver,          2) \
X(a, STATIC,   OPTIONAL, BOOL,     ptt,               4)
#define makesdr_BasicRxSettingsPb_CALLBACK NULL
#define makesdr_BasicRxSettingsPb_DEFAULT NULL
#define makesdr_BasicRxSettingsPb_active_bands_MSGTYPE makesdr_BasicActiveBandSettingsPb
#define makesdr_BasicRxSettingsPb_receiver_MSGTYPE makesdr_ReceiverSettingsPb

#define makesdr_BasicIqRxSettingsPb_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  active_bands,      1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  receiver,          2) \
X(a, STATIC,   OPTIONAL, BOOL,     ptt,               4)
#define makesdr_BasicIqRxSettingsPb_CALLBACK NULL
#define makesdr_BasicIqRxSettingsPb_DEFAULT NULL
#define makesdr_BasicIqRxSettingsPb_active_bands_MSGTYPE makesdr_BasicIqActiveBandSettingsPb
#define makesdr_BasicIqRxSettingsPb_receiver_MSGTYPE makesdr_ReceiverSettingsPb

#define makesdr_DualIqRxSettingsPb_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  active_bands,      1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  receiver,          2) \
X(a, STATIC,   OPTIONAL, BOOL,     ptt,               4)
#define makesdr_DualIqRxSettingsPb_CALLBACK NULL
#define makesdr_DualIqRxSettingsPb_DEFAULT NULL
#define makesdr_DualIqRxSettingsPb_active_bands_MSGTYPE makesdr_DualIqActiveBandSettingsPb
#define makesdr_DualIqRxSettingsPb_receiver_MSGTYPE makesdr_ReceiverSettingsPb

#define makesdr_BasicRxTxSettingsPb_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  active_bands,      1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  receiver,          2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  transmitter,       3) \
X(a, STATIC,   OPTIONAL, BOOL,     ptt,               4)
#define makesdr_BasicRxTxSettingsPb_CALLBACK NULL
#define makesdr_BasicRxTxSettingsPb_DEFAULT NULL
#define makesdr_BasicRxTxSettingsPb_active_bands_MSGTYPE makesdr_BasicActiveBandSettingsPb
#define makesdr_BasicRxTxSettingsPb_receiver_MSGTYPE makesdr_ReceiverSettingsPb
#define makesdr_BasicRxTxSettingsPb_transmitter_MSGTYPE makesdr_TransmitterSettingsPb

#define makesdr_BasicIqRxTxSettingsPb_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  active_bands,      1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  receiver,          2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  transmitter,       3) \
X(a, STATIC,   OPTIONAL, BOOL,     ptt,               4)
#define makesdr_BasicIqRxTxSettingsPb_CALLBACK NULL
#define makesdr_BasicIqRxTxSettingsPb_DEFAULT NULL
#define makesdr_BasicIqRxTxSettingsPb_active_bands_MSGTYPE makesdr_BasicIqActiveBandSettingsPb
#define makesdr_BasicIqRxTxSettingsPb_receiver_MSGTYPE makesdr_ReceiverSettingsPb
#define makesdr_BasicIqRxTxSettingsPb_transmitter_MSGTYPE makesdr_TransmitterSettingsPb

#define makesdr_DualIqRxTxSettingsPb_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  active_bands,      1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  receiver,          2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  transmitter,       3) \
X(a, STATIC,   OPTIONAL, BOOL,     ptt,               4)
#define makesdr_DualIqRxTxSettingsPb_CALLBACK NULL
#define makesdr_DualIqRxTxSettingsPb_DEFAULT NULL
#define makesdr_DualIqRxTxSettingsPb_active_bands_MSGTYPE makesdr_RxTxDualIqActiveBandSettingsPb
#define makesdr_DualIqRxTxSettingsPb_receiver_MSGTYPE makesdr_ReceiverSettingsPb
#define makesdr_DualIqRxTxSettingsPb_transmitter_MSGTYPE makesdr_TransmitterSettingsPb

#define makesdr_SplitBandDualIqRxTxSettingsPb_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  active_bands,      1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  receiver,          2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  transmitter,       3) \
X(a, STATIC,   OPTIONAL, BOOL,     ptt,               4)
#define makesdr_SplitBandDualIqRxTxSettingsPb_CALLBACK NULL
#define makesdr_SplitBandDualIqRxTxSettingsPb_DEFAULT NULL
#define makesdr_SplitBandDualIqRxTxSettingsPb_active_bands_MSGTYPE makesdr_SplitBandDualIqActiveBandSettingsPb
#define makesdr_SplitBandDualIqRxTxSettingsPb_receiver_MSGTYPE makesdr_ReceiverSettingsPb
#define makesdr_SplitBandDualIqRxTxSettingsPb_transmitter_MSGTYPE makesdr_TransmitterSettingsPb

#define makesdr_FieldUpdatePb_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, UINT32,   path,              1) \
X(a, STATIC,   ONEOF,    STRING,   (value_variant,string_value,value_variant.string_value),   2) \
X(a, STATIC,   ONEOF,    INT32,    (value_variant,int32_value,value_variant.int32_value),   3) \
X(a, STATIC,   ONEOF,    UINT32,   (value_variant,uint32_value,value_variant.uint32_value),   4) \
X(a, STATIC,   ONEOF,    INT64,    (value_variant,int64_value,value_variant.int64_value),   5) \
X(a, STATIC,   ONEOF,    FLOAT,    (value_variant,float_value,value_variant.float_value),   6) \
X(a, STATIC,   ONEOF,    BOOL,     (value_variant,bool_value,value_variant.bool_value),   7) \
X(a, STATIC,   SINGULAR, UENUM,    meaning,          10) \
X(a, STATIC,   SINGULAR, BOOL,     is_indirect,      11) \
X(a, STATIC,   SINGULAR, BOOL,     is_auto_complete,  12) \
X(a, STATIC,   SINGULAR, BOOL,     is_final,         13)
#define makesdr_FieldUpdatePb_CALLBACK NULL
#define makesdr_FieldUpdatePb_DEFAULT NULL

extern const pb_msgdesc_t makesdr_ModePb_msg;
extern const pb_msgdesc_t makesdr_ModeListPb_msg;
extern const pb_msgdesc_t makesdr_BandPb_msg;
extern const pb_msgdesc_t makesdr_BandListPb_msg;
extern const pb_msgdesc_t makesdr_BandCategoryPb_msg;
extern const pb_msgdesc_t makesdr_BandCategoryListPb_msg;
extern const pb_msgdesc_t makesdr_RadioLookupPb_msg;
extern const pb_msgdesc_t makesdr_SteppableInt64SettingPb_msg;
extern const pb_msgdesc_t makesdr_SteppableFloatSettingPb_msg;
extern const pb_msgdesc_t makesdr_IqCorrectionSettingsPb_msg;
extern const pb_msgdesc_t makesdr_BandRfSettingsPb_msg;
extern const pb_msgdesc_t makesdr_PipelineRfSettingsPb_msg;
extern const pb_msgdesc_t makesdr_IfSettingsPb_msg;
extern const pb_msgdesc_t makesdr_AfSettingsPb_msg;
extern const pb_msgdesc_t makesdr_ReceiverSettingsPb_msg;
extern const pb_msgdesc_t makesdr_TransmitterSettingsPb_msg;
extern const pb_msgdesc_t makesdr_PipelineSettingsPb_msg;
extern const pb_msgdesc_t makesdr_RxPipelineSettingsPb_msg;
extern const pb_msgdesc_t makesdr_TxPipelineSettingsPb_msg;
extern const pb_msgdesc_t makesdr_BasicBandSettingsPb_msg;
extern const pb_msgdesc_t makesdr_BasicIqBandSettingsPb_msg;
extern const pb_msgdesc_t makesdr_DualIqBandSettingsPb_msg;
extern const pb_msgdesc_t makesdr_RxTxDualIqBandSettingsPb_msg;
extern const pb_msgdesc_t makesdr_BasicActiveBandSettingsPb_msg;
extern const pb_msgdesc_t makesdr_BasicIqActiveBandSettingsPb_msg;
extern const pb_msgdesc_t makesdr_DualIqActiveBandSettingsPb_msg;
extern const pb_msgdesc_t makesdr_RxTxDualIqActiveBandSettingsPb_msg;
extern const pb_msgdesc_t makesdr_SplitBandDualIqActiveBandSettingsPb_msg;
extern const pb_msgdesc_t makesdr_BasicBandSettingsCachePb_msg;
extern const pb_msgdesc_t makesdr_BasicBandSettingsCachePb_BandSettingsEntry_msg;
extern const pb_msgdesc_t makesdr_BasicIqBandSettingsCachePb_msg;
extern const pb_msgdesc_t makesdr_BasicIqBandSettingsCachePb_BandSettingsEntry_msg;
extern const pb_msgdesc_t makesdr_DualIqBandSettingsCachePb_msg;
extern const pb_msgdesc_t makesdr_DualIqBandSettingsCachePb_BandSettingsEntry_msg;
extern const pb_msgdesc_t makesdr_RxTxDualIqBandSettingsCachePb_msg;
extern const pb_msgdesc_t makesdr_RxTxDualIqBandSettingsCachePb_BandSettingsEntry_msg;
extern const pb_msgdesc_t makesdr_BasicRxSettingsPb_msg;
extern const pb_msgdesc_t makesdr_BasicIqRxSettingsPb_msg;
extern const pb_msgdesc_t makesdr_DualIqRxSettingsPb_msg;
extern const pb_msgdesc_t makesdr_BasicRxTxSettingsPb_msg;
extern const pb_msgdesc_t makesdr_BasicIqRxTxSettingsPb_msg;
extern const pb_msgdesc_t makesdr_DualIqRxTxSettingsPb_msg;
extern const pb_msgdesc_t makesdr_SplitBandDualIqRxTxSettingsPb_msg;
extern const pb_msgdesc_t makesdr_FieldUpdatePb_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define makesdr_ModePb_fields &makesdr_ModePb_msg
#define makesdr_ModeListPb_fields &makesdr_ModeListPb_msg
#define makesdr_BandPb_fields &makesdr_BandPb_msg
#define makesdr_BandListPb_fields &makesdr_BandListPb_msg
#define makesdr_BandCategoryPb_fields &makesdr_BandCategoryPb_msg
#define makesdr_BandCategoryListPb_fields &makesdr_BandCategoryListPb_msg
#define makesdr_RadioLookupPb_fields &makesdr_RadioLookupPb_msg
#define makesdr_SteppableInt64SettingPb_fields &makesdr_SteppableInt64SettingPb_msg
#define makesdr_SteppableFloatSettingPb_fields &makesdr_SteppableFloatSettingPb_msg
#define makesdr_IqCorrectionSettingsPb_fields &makesdr_IqCorrectionSettingsPb_msg
#define makesdr_BandRfSettingsPb_fields &makesdr_BandRfSettingsPb_msg
#define makesdr_PipelineRfSettingsPb_fields &makesdr_PipelineRfSettingsPb_msg
#define makesdr_IfSettingsPb_fields &makesdr_IfSettingsPb_msg
#define makesdr_AfSettingsPb_fields &makesdr_AfSettingsPb_msg
#define makesdr_ReceiverSettingsPb_fields &makesdr_ReceiverSettingsPb_msg
#define makesdr_TransmitterSettingsPb_fields &makesdr_TransmitterSettingsPb_msg
#define makesdr_PipelineSettingsPb_fields &makesdr_PipelineSettingsPb_msg
#define makesdr_RxPipelineSettingsPb_fields &makesdr_RxPipelineSettingsPb_msg
#define makesdr_TxPipelineSettingsPb_fields &makesdr_TxPipelineSettingsPb_msg
#define makesdr_BasicBandSettingsPb_fields &makesdr_BasicBandSettingsPb_msg
#define makesdr_BasicIqBandSettingsPb_fields &makesdr_BasicIqBandSettingsPb_msg
#define makesdr_DualIqBandSettingsPb_fields &makesdr_DualIqBandSettingsPb_msg
#define makesdr_RxTxDualIqBandSettingsPb_fields &makesdr_RxTxDualIqBandSettingsPb_msg
#define makesdr_BasicActiveBandSettingsPb_fields &makesdr_BasicActiveBandSettingsPb_msg
#define makesdr_BasicIqActiveBandSettingsPb_fields &makesdr_BasicIqActiveBandSettingsPb_msg
#define makesdr_DualIqActiveBandSettingsPb_fields &makesdr_DualIqActiveBandSettingsPb_msg
#define makesdr_RxTxDualIqActiveBandSettingsPb_fields &makesdr_RxTxDualIqActiveBandSettingsPb_msg
#define makesdr_SplitBandDualIqActiveBandSettingsPb_fields &makesdr_SplitBandDualIqActiveBandSettingsPb_msg
#define makesdr_BasicBandSettingsCachePb_fields &makesdr_BasicBandSettingsCachePb_msg
#define makesdr_BasicBandSettingsCachePb_BandSettingsEntry_fields &makesdr_BasicBandSettingsCachePb_BandSettingsEntry_msg
#define makesdr_BasicIqBandSettingsCachePb_fields &makesdr_BasicIqBandSettingsCachePb_msg
#define makesdr_BasicIqBandSettingsCachePb_BandSettingsEntry_fields &makesdr_BasicIqBandSettingsCachePb_BandSettingsEntry_msg
#define makesdr_DualIqBandSettingsCachePb_fields &makesdr_DualIqBandSettingsCachePb_msg
#define makesdr_DualIqBandSettingsCachePb_BandSettingsEntry_fields &makesdr_DualIqBandSettingsCachePb_BandSettingsEntry_msg
#define makesdr_RxTxDualIqBandSettingsCachePb_fields &makesdr_RxTxDualIqBandSettingsCachePb_msg
#define makesdr_RxTxDualIqBandSettingsCachePb_BandSettingsEntry_fields &makesdr_RxTxDualIqBandSettingsCachePb_BandSettingsEntry_msg
#define makesdr_BasicRxSettingsPb_fields &makesdr_BasicRxSettingsPb_msg
#define makesdr_BasicIqRxSettingsPb_fields &makesdr_BasicIqRxSettingsPb_msg
#define makesdr_DualIqRxSettingsPb_fields &makesdr_DualIqRxSettingsPb_msg
#define makesdr_BasicRxTxSettingsPb_fields &makesdr_BasicRxTxSettingsPb_msg
#define makesdr_BasicIqRxTxSettingsPb_fields &makesdr_BasicIqRxTxSettingsPb_msg
#define makesdr_DualIqRxTxSettingsPb_fields &makesdr_DualIqRxTxSettingsPb_msg
#define makesdr_SplitBandDualIqRxTxSettingsPb_fields &makesdr_SplitBandDualIqRxTxSettingsPb_msg
#define makesdr_FieldUpdatePb_fields &makesdr_FieldUpdatePb_msg

/* Maximum encoded size of messages (where known) */
#define MAKESDR_RADIOSETTINGS_PB_H_MAX_SIZE      makesdr_RadioLookupPb_size
#define makesdr_AfSettingsPb_size                20
#define makesdr_BandCategoryListPb_size          8424
#define makesdr_BandCategoryPb_size              1050
#define makesdr_BandListPb_size                  1027
#define makesdr_BandPb_size                      77
#define makesdr_BandRfSettingsPb_size            58
#define makesdr_BasicActiveBandSettingsPb_size   234
#define makesdr_BasicBandSettingsCachePb_BandSettingsEntry_size 243
#define makesdr_BasicBandSettingsCachePb_size    2460
#define makesdr_BasicBandSettingsPb_size         231
#define makesdr_BasicIqActiveBandSettingsPb_size 346
#define makesdr_BasicIqBandSettingsCachePb_BandSettingsEntry_size 355
#define makesdr_BasicIqBandSettingsCachePb_size  3580
#define makesdr_BasicIqBandSettingsPb_size       343
#define makesdr_BasicIqRxSettingsPb_size         375
#define makesdr_BasicIqRxTxSettingsPb_size       399
#define makesdr_BasicRxSettingsPb_size           263
#define makesdr_BasicRxTxSettingsPb_size         287
#define makesdr_DualIqActiveBandSettingsPb_size  528
#define makesdr_DualIqBandSettingsCachePb_BandSettingsEntry_size 537
#define makesdr_DualIqBandSettingsCachePb_size   5400
#define makesdr_DualIqBandSettingsPb_size        525
#define makesdr_DualIqRxSettingsPb_size          557
#define makesdr_DualIqRxTxSettingsPb_size        756
#define makesdr_FieldUpdatePb_size               67
#define makesdr_IfSettingsPb_size                26
#define makesdr_IqCorrectionSettingsPb_size      40
#define makesdr_ModeListPb_size                  620
#define makesdr_ModePb_size                      60
#define makesdr_PipelineRfSettingsPb_size        60
#define makesdr_PipelineSettingsPb_size          166
#define makesdr_RadioLookupPb_size               9050
#define makesdr_ReceiverSettingsPb_size          22
#define makesdr_RxPipelineSettingsPb_size        173
#define makesdr_RxTxDualIqActiveBandSettingsPb_size 703
#define makesdr_RxTxDualIqBandSettingsCachePb_BandSettingsEntry_size 712
#define makesdr_RxTxDualIqBandSettingsCachePb_size 7150
#define makesdr_RxTxDualIqBandSettingsPb_size    700
#define makesdr_SplitBandDualIqActiveBandSettingsPb_size 1416
#define makesdr_SplitBandDualIqRxTxSettingsPb_size 1469
#define makesdr_SteppableFloatSettingPb_size     17
#define makesdr_SteppableInt64SettingPb_size     35
#define makesdr_TransmitterSettingsPb_size       22
#define makesdr_TxPipelineSettingsPb_size        169

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
