/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_MAKESDR_RADIOPAYLOADS_PB_H_INCLUDED
#define PB_MAKESDR_RADIOPAYLOADS_PB_H_INCLUDED
#include <pb.h>
#include "RadioSettings.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _makesdr_RadioPayloadType {
    makesdr_RadioPayloadType_PAYLOAD_NONE = 0,
    makesdr_RadioPayloadType_PAYLOAD_SETTINGS = 1,
    makesdr_RadioPayloadType_PAYLOAD_META = 3,
    makesdr_RadioPayloadType_PAYLOAD_CACHE = 4
} makesdr_RadioPayloadType;

typedef enum _makesdr_RadioPayloadPurpose {
    makesdr_RadioPayloadPurpose_PURPOSE_NONE = 0,
    makesdr_RadioPayloadPurpose_PURPOSE_MERGE = 1,
    makesdr_RadioPayloadPurpose_PURPOSE_REPLACE = 2
} makesdr_RadioPayloadPurpose;

/* Struct definitions */
typedef struct _makesdr_RadioPayloadHeaderPb {
    makesdr_RadioPayloadType payloadType;
} makesdr_RadioPayloadHeaderPb;

typedef struct _makesdr_RadioPayloadBasePb {
    bool has_header;
    makesdr_RadioPayloadHeaderPb header;
} makesdr_RadioPayloadBasePb;

typedef struct _makesdr_RadioSettingsPayloadPb {
    bool has_header;
    makesdr_RadioPayloadHeaderPb header;
    makesdr_RadioPayloadPurpose purpose;
    bool has_body;
    makesdr_RadioSettingsPb body;
} makesdr_RadioSettingsPayloadPb;

typedef struct _makesdr_RadioMetaPayloadPb {
    bool has_header;
    makesdr_RadioPayloadHeaderPb header;
    bool has_body;
    makesdr_RadioMetaPb body;
} makesdr_RadioMetaPayloadPb;

typedef struct _makesdr_RadioCachePayloadPb {
    makesdr_RadioPayloadType payloadType;
    bool has_body;
    makesdr_RadioMetaPb body;
} makesdr_RadioCachePayloadPb;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _makesdr_RadioPayloadType_MIN makesdr_RadioPayloadType_PAYLOAD_NONE
#define _makesdr_RadioPayloadType_MAX makesdr_RadioPayloadType_PAYLOAD_CACHE
#define _makesdr_RadioPayloadType_ARRAYSIZE ((makesdr_RadioPayloadType)(makesdr_RadioPayloadType_PAYLOAD_CACHE+1))

#define _makesdr_RadioPayloadPurpose_MIN makesdr_RadioPayloadPurpose_PURPOSE_NONE
#define _makesdr_RadioPayloadPurpose_MAX makesdr_RadioPayloadPurpose_PURPOSE_REPLACE
#define _makesdr_RadioPayloadPurpose_ARRAYSIZE ((makesdr_RadioPayloadPurpose)(makesdr_RadioPayloadPurpose_PURPOSE_REPLACE+1))

#define makesdr_RadioPayloadHeaderPb_payloadType_ENUMTYPE makesdr_RadioPayloadType


#define makesdr_RadioSettingsPayloadPb_purpose_ENUMTYPE makesdr_RadioPayloadPurpose


#define makesdr_RadioCachePayloadPb_payloadType_ENUMTYPE makesdr_RadioPayloadType


/* Initializer values for message structs */
#define makesdr_RadioPayloadHeaderPb_init_default {_makesdr_RadioPayloadType_MIN}
#define makesdr_RadioPayloadBasePb_init_default  {false, makesdr_RadioPayloadHeaderPb_init_default}
#define makesdr_RadioSettingsPayloadPb_init_default {false, makesdr_RadioPayloadHeaderPb_init_default, _makesdr_RadioPayloadPurpose_MIN, false, makesdr_RadioSettingsPb_init_default}
#define makesdr_RadioMetaPayloadPb_init_default  {false, makesdr_RadioPayloadHeaderPb_init_default, false, makesdr_RadioMetaPb_init_default}
#define makesdr_RadioCachePayloadPb_init_default {_makesdr_RadioPayloadType_MIN, false, makesdr_RadioMetaPb_init_default}
#define makesdr_RadioPayloadHeaderPb_init_zero   {_makesdr_RadioPayloadType_MIN}
#define makesdr_RadioPayloadBasePb_init_zero     {false, makesdr_RadioPayloadHeaderPb_init_zero}
#define makesdr_RadioSettingsPayloadPb_init_zero {false, makesdr_RadioPayloadHeaderPb_init_zero, _makesdr_RadioPayloadPurpose_MIN, false, makesdr_RadioSettingsPb_init_zero}
#define makesdr_RadioMetaPayloadPb_init_zero     {false, makesdr_RadioPayloadHeaderPb_init_zero, false, makesdr_RadioMetaPb_init_zero}
#define makesdr_RadioCachePayloadPb_init_zero    {_makesdr_RadioPayloadType_MIN, false, makesdr_RadioMetaPb_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define makesdr_RadioPayloadHeaderPb_payloadType_tag 1
#define makesdr_RadioPayloadBasePb_header_tag    1
#define makesdr_RadioSettingsPayloadPb_header_tag 1
#define makesdr_RadioSettingsPayloadPb_purpose_tag 2
#define makesdr_RadioSettingsPayloadPb_body_tag  3
#define makesdr_RadioMetaPayloadPb_header_tag    1
#define makesdr_RadioMetaPayloadPb_body_tag      2
#define makesdr_RadioCachePayloadPb_payloadType_tag 1
#define makesdr_RadioCachePayloadPb_body_tag     2

/* Struct field encoding specification for nanopb */
#define makesdr_RadioPayloadHeaderPb_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    payloadType,       1)
#define makesdr_RadioPayloadHeaderPb_CALLBACK NULL
#define makesdr_RadioPayloadHeaderPb_DEFAULT NULL

#define makesdr_RadioPayloadBasePb_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1)
#define makesdr_RadioPayloadBasePb_CALLBACK NULL
#define makesdr_RadioPayloadBasePb_DEFAULT NULL
#define makesdr_RadioPayloadBasePb_header_MSGTYPE makesdr_RadioPayloadHeaderPb

#define makesdr_RadioSettingsPayloadPb_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   SINGULAR, UENUM,    purpose,           2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  body,              3)
#define makesdr_RadioSettingsPayloadPb_CALLBACK NULL
#define makesdr_RadioSettingsPayloadPb_DEFAULT NULL
#define makesdr_RadioSettingsPayloadPb_header_MSGTYPE makesdr_RadioPayloadHeaderPb
#define makesdr_RadioSettingsPayloadPb_body_MSGTYPE makesdr_RadioSettingsPb

#define makesdr_RadioMetaPayloadPb_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  body,              2)
#define makesdr_RadioMetaPayloadPb_CALLBACK NULL
#define makesdr_RadioMetaPayloadPb_DEFAULT NULL
#define makesdr_RadioMetaPayloadPb_header_MSGTYPE makesdr_RadioPayloadHeaderPb
#define makesdr_RadioMetaPayloadPb_body_MSGTYPE makesdr_RadioMetaPb

#define makesdr_RadioCachePayloadPb_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    payloadType,       1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  body,              2)
#define makesdr_RadioCachePayloadPb_CALLBACK NULL
#define makesdr_RadioCachePayloadPb_DEFAULT NULL
#define makesdr_RadioCachePayloadPb_body_MSGTYPE makesdr_RadioMetaPb

extern const pb_msgdesc_t makesdr_RadioPayloadHeaderPb_msg;
extern const pb_msgdesc_t makesdr_RadioPayloadBasePb_msg;
extern const pb_msgdesc_t makesdr_RadioSettingsPayloadPb_msg;
extern const pb_msgdesc_t makesdr_RadioMetaPayloadPb_msg;
extern const pb_msgdesc_t makesdr_RadioCachePayloadPb_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define makesdr_RadioPayloadHeaderPb_fields &makesdr_RadioPayloadHeaderPb_msg
#define makesdr_RadioPayloadBasePb_fields &makesdr_RadioPayloadBasePb_msg
#define makesdr_RadioSettingsPayloadPb_fields &makesdr_RadioSettingsPayloadPb_msg
#define makesdr_RadioMetaPayloadPb_fields &makesdr_RadioMetaPayloadPb_msg
#define makesdr_RadioCachePayloadPb_fields &makesdr_RadioCachePayloadPb_msg

/* Maximum encoded size of messages (where known) */
#define MAKESDR_RADIOPAYLOADS_PB_H_MAX_SIZE      makesdr_RadioMetaPayloadPb_size
#define makesdr_RadioCachePayloadPb_size         9055
#define makesdr_RadioMetaPayloadPb_size          9057
#define makesdr_RadioPayloadBasePb_size          4
#define makesdr_RadioPayloadHeaderPb_size        2
#define makesdr_RadioSettingsPayloadPb_size      1570

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
